// mockdata for property cards

export const cards = [
    {
      image:
        "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Skyline Heights",
      developer: "Urban Edge Properties",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "123 Liberty St, New York, NY",
      walkingTime: "5",
      isPopular: true,
      isCompleted: true,
      amenities: [
        "Rooftop garden",
        "24/7 security",
        "Fitness center",
        "Co-working space",
        "Indoor pool",
        "Pet-friendly",
        "Concierge service",
        "Private theater",
      ],
      layouts: [
        { type: "Studio", count: 5, price: "1,200,000" },
        { type: "1 Bedroom", count: 10, price: "1,800,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Oceanview Residences",
      developer: "Seaside Developments",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "456 Ocean Ave, Santa Monica, CA",
      walkingTime: "2",
      isPopular: true,
      isCompleted: false,
      amenities: [
        "Beach access",
        "Infinity pool",
        "Spa and wellness center",
        "Gourmet dining",
        "Yoga studio",
        "Valet parking",
        "Private balconies",
        "Smart home technology",
      ],
      layouts: [
        { type: "2 Bedrooms", count: 8, price: "2,500,000" },
        { type: "3 Bedrooms", count: 4, price: "3,800,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Mountain Retreat",
      developer: "Highland Estates",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "789 Alpine Rd, Aspen, CO",
      walkingTime: "10",
      isPopular: false,
      isCompleted: true,
      amenities: [
        "Ski-in/ski-out access",
        "Heated floors",
        "Fireplace lounges",
        "Private hot tubs",
        "Gourmet kitchens",
        "Wine cellars",
        "Home theaters",
        "Game rooms",
      ],
      layouts: [
        { type: "3 Bedrooms", count: 6, price: "4,200,000" },
        { type: "4 Bedrooms", count: 2, price: "5,600,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Urban Oasis",
      developer: "Cityscape Builders",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "321 Wacker Dr, Chicago, IL",
      walkingTime: "3",
      isPopular: true,
      isCompleted: false,
      amenities: [
        "Sky lounge",
        "Fitness center",
        "Indoor pool",
        "Business center",
        "Pet spa",
        "Outdoor terrace",
        "Bike storage",
        "On-site retail",
      ],
      layouts: [
        { type: "1 Bedroom", count: 12, price: "950,000" },
        { type: "2 Bedrooms", count: 8, price: "1,400,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Lakeside Villas",
      developer: "Tranquil Living",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "654 Serenity Ln, South Lake Tahoe, CA",
      walkingTime: "7",
      isPopular: false,
      isCompleted: true,
      amenities: [
        "Private docks",
        "Lakeside views",
        "Gourmet kitchens",
        "Fire pits",
        "Outdoor kitchens",
        "Jacuzzis",
        "Home automation",
        "Security systems",
      ],
      layouts: [
        { type: "2 Bedrooms", count: 10, price: "2,200,000" },
        { type: "3 Bedrooms", count: 5, price: "3,100,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Countryside Manor",
      developer: "Heritage Homes",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "987 Country Rd, Nashville, TN",
      walkingTime: "15",
      isPopular: false,
      isCompleted: false,
      amenities: [
        "Horse stables",
        "Private gardens",
        "Gated entry",
        "Chef's kitchen",
        "Wine cellar",
        "Library",
        "Home office",
        "Outdoor pool",
      ],
      layouts: [
        { type: "4 Bedrooms", count: 3, price: "3,500,000" },
        { type: "5 Bedrooms", count: 2, price: "4,700,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Seaside Escape",
      developer: "Coastal Builders",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "123 Ocean Drive, Miami Beach, FL",
      walkingTime: "2",
      isPopular: true,
      isCompleted: true,
      amenities: [
        "Horse stables",
        "Private gardens",
        "Gated entry",
        "Chef's kitchen",
        "Wine cellar",
        "Library",
        "Home office",
        "Outdoor pool",
      ],
      layouts: [
        { type: "4 Bedrooms", count: 3, price: "3,500,000" },
        { type: "5 Bedrooms", count: 2, price: "4,700,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Sky Tower",
      developer: "Metropolitan Properties",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "789 Market St, San Francisco, CA",
      walkingTime: "5",
      isPopular: true,
      isCompleted: false,
      amenities: [
        "Rooftop infinity pool",
        "24/7 concierge",
        "Luxury spa",
        "Movie theater",
        "Private lounges",
        "Gourmet dining options",
        "Pet-friendly facilities",
        "Smart home automation",
      ],
      layouts: [
        { type: "Studio", count: 4, price: "1,500,000" },
        { type: "1 Bedroom", count: 10, price: "2,100,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/136407/pexels-photo-136407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Palm Grove Residences",
      developer: "Sunset Developers",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "567 Sunset Blvd, Los Angeles, CA",
      walkingTime: "3",
      isPopular: true,
      isCompleted: true,
      amenities: [
        "Private rooftop gardens",
        "Resort-style pool",
        "Full-service gym",
        "High-speed internet",
        "Pet park",
        "Personalized butler service",
        "Exclusive residents' club",
        "State-of-the-art security",
      ],
      layouts: [
        { type: "1 Bedroom", count: 8, price: "2,300,000" },
        { type: "2 Bedrooms", count: 6, price: "3,200,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/208736/pexels-photo-208736.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Evergreen Towers",
      developer: "Green Living Estates",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "222 Pine St, Seattle, WA",
      walkingTime: "4",
      isPopular: false,
      isCompleted: true,
      amenities: [
        "Eco-friendly design",
        "Solar energy solutions",
        "Community garden",
        "Yoga & meditation rooms",
        "Private balconies",
        "On-site co-working space",
        "EV charging stations",
        "Luxury clubhouse",
      ],
      layouts: [
        { type: "Studio", count: 5, price: "1,300,000" },
        { type: "1 Bedroom", count: 7, price: "1,900,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Central Park Lofts",
      developer: "Modern Living Developers",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "101 5th Ave, Manhattan, NY",
      walkingTime: "2",
      isPopular: true,
      isCompleted: false,
      amenities: [
        "Private rooftop terraces",
        "Gym with personal trainers",
        "Luxury spa treatments",
        "High-speed elevators",
        "On-site wine bar",
        "Concierge for residents",
        "Soundproof music rooms",
        "Exclusive shopping access",
      ],
      layouts: [
        { type: "Loft", count: 4, price: "3,100,000" },
        { type: "2 Bedrooms", count: 6, price: "4,500,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Lakeside Villas",
      developer: "Tranquil Living",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "654 Serenity Ln, South Lake Tahoe, CA",
      walkingTime: "7",
      isPopular: false,
      isCompleted: true,
      amenities: [
        "Private docks",
        "Lakeside views",
        "Gourmet kitchens",
        "Fire pits",
        "Outdoor kitchens",
        "Jacuzzis",
        "Home automation",
        "Security systems",
      ],
      layouts: [
        { type: "2 Bedrooms", count: 10, price: "2,200,000" },
        { type: "3 Bedrooms", count: 5, price: "3,100,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Countryside Manor",
      developer: "Heritage Homes",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "987 Country Rd, Nashville, TN",
      walkingTime: "15",
      isPopular: false,
      isCompleted: false,
      amenities: [
        "Horse stables",
        "Private gardens",
        "Gated entry",
        "Chef's kitchen",
        "Wine cellar",
        "Library",
        "Home office",
        "Outdoor pool",
      ],
      layouts: [
        { type: "4 Bedrooms", count: 3, price: "3,500,000" },
        { type: "5 Bedrooms", count: 2, price: "4,700,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Seaside Escape",
      developer: "Coastal Builders",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "123 Ocean Drive, Miami Beach, FL",
      walkingTime: "2",
      isPopular: true,
      isCompleted: true,
      amenities: [
        "Horse stables",
        "Private gardens",
        "Gated entry",
        "Chef's kitchen",
        "Wine cellar",
        "Library",
        "Home office",
        "Outdoor pool",
      ],
      layouts: [
        { type: "4 Bedrooms", count: 3, price: "3,500,000" },
        { type: "5 Bedrooms", count: 2, price: "4,700,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Sky Tower",
      developer: "Metropolitan Properties",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "789 Market St, San Francisco, CA",
      walkingTime: "5",
      isPopular: true,
      isCompleted: false,
      amenities: [
        "Rooftop infinity pool",
        "24/7 concierge",
        "Luxury spa",
        "Movie theater",
        "Private lounges",
        "Gourmet dining options",
        "Pet-friendly facilities",
        "Smart home automation",
      ],
      layouts: [
        { type: "Studio", count: 4, price: "1,500,000" },
        { type: "1 Bedroom", count: 10, price: "2,100,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/136407/pexels-photo-136407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Palm Grove Residences",
      developer: "Sunset Developers",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "567 Sunset Blvd, Los Angeles, CA",
      walkingTime: "3",
      isPopular: true,
      isCompleted: true,
      amenities: [
        "Private rooftop gardens",
        "Resort-style pool",
        "Full-service gym",
        "High-speed internet",
        "Pet park",
        "Personalized butler service",
        "Exclusive residents' club",
        "State-of-the-art security",
      ],
      layouts: [
        { type: "1 Bedroom", count: 8, price: "2,300,000" },
        { type: "2 Bedrooms", count: 6, price: "3,200,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/208736/pexels-photo-208736.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Evergreen Towers",
      developer: "Green Living Estates",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "222 Pine St, Seattle, WA",
      walkingTime: "4",
      isPopular: false,
      isCompleted: true,
      amenities: [
        "Eco-friendly design",
        "Solar energy solutions",
        "Community garden",
        "Yoga & meditation rooms",
        "Private balconies",
        "On-site co-working space",
        "EV charging stations",
        "Luxury clubhouse",
      ],
      layouts: [
        { type: "Studio", count: 5, price: "1,300,000" },
        { type: "1 Bedroom", count: 7, price: "1,900,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Central Park Lofts",
      developer: "Modern Living Developers",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "101 5th Ave, Manhattan, NY",
      walkingTime: "2",
      isPopular: true,
      isCompleted: false,
      amenities: [
        "Private rooftop terraces",
        "Gym with personal trainers",
        "Luxury spa treatments",
        "High-speed elevators",
        "On-site wine bar",
        "Concierge for residents",
        "Soundproof music rooms",
        "Exclusive shopping access",
      ],
      layouts: [
        { type: "Loft", count: 4, price: "3,100,000" },
        { type: "2 Bedrooms", count: 6, price: "4,500,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Lakeside Villas",
      developer: "Tranquil Living",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "654 Serenity Ln, South Lake Tahoe, CA",
      walkingTime: "7",
      isPopular: false,
      isCompleted: true,
      amenities: [
        "Private docks",
        "Lakeside views",
        "Gourmet kitchens",
        "Fire pits",
        "Outdoor kitchens",
        "Jacuzzis",
        "Home automation",
        "Security systems",
      ],
      layouts: [
        { type: "2 Bedrooms", count: 10, price: "2,200,000" },
        { type: "3 Bedrooms", count: 5, price: "3,100,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Countryside Manor",
      developer: "Heritage Homes",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "987 Country Rd, Nashville, TN",
      walkingTime: "15",
      isPopular: false,
      isCompleted: false,
      amenities: [
        "Horse stables",
        "Private gardens",
        "Gated entry",
        "Chef's kitchen",
        "Wine cellar",
        "Library",
        "Home office",
        "Outdoor pool",
      ],
      layouts: [
        { type: "4 Bedrooms", count: 3, price: "3,500,000" },
        { type: "5 Bedrooms", count: 2, price: "4,700,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Seaside Escape",
      developer: "Coastal Builders",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "123 Ocean Drive, Miami Beach, FL",
      walkingTime: "2",
      isPopular: true,
      isCompleted: true,
      amenities: [
        "Horse stables",
        "Private gardens",
        "Gated entry",
        "Chef's kitchen",
        "Wine cellar",
        "Library",
        "Home office",
        "Outdoor pool",
      ],
      layouts: [
        { type: "4 Bedrooms", count: 3, price: "3,500,000" },
        { type: "5 Bedrooms", count: 2, price: "4,700,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Sky Tower",
      developer: "Metropolitan Properties",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "789 Market St, San Francisco, CA",
      walkingTime: "5",
      isPopular: true,
      isCompleted: false,
      amenities: [
        "Rooftop infinity pool",
        "24/7 concierge",
        "Luxury spa",
        "Movie theater",
        "Private lounges",
        "Gourmet dining options",
        "Pet-friendly facilities",
        "Smart home automation",
      ],
      layouts: [
        { type: "Studio", count: 4, price: "1,500,000" },
        { type: "1 Bedroom", count: 10, price: "2,100,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/136407/pexels-photo-136407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Palm Grove Residences",
      developer: "Sunset Developers",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "567 Sunset Blvd, Los Angeles, CA",
      walkingTime: "3",
      isPopular: true,
      isCompleted: true,
      amenities: [
        "Private rooftop gardens",
        "Resort-style pool",
        "Full-service gym",
        "High-speed internet",
        "Pet park",
        "Personalized butler service",
        "Exclusive residents' club",
        "State-of-the-art security",
      ],
      layouts: [
        { type: "1 Bedroom", count: 8, price: "2,300,000" },
        { type: "2 Bedrooms", count: 6, price: "3,200,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/208736/pexels-photo-208736.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Evergreen Towers",
      developer: "Green Living Estates",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "222 Pine St, Seattle, WA",
      walkingTime: "4",
      isPopular: false,
      isCompleted: true,
      amenities: [
        "Eco-friendly design",
        "Solar energy solutions",
        "Community garden",
        "Yoga & meditation rooms",
        "Private balconies",
        "On-site co-working space",
        "EV charging stations",
        "Luxury clubhouse",
      ],
      layouts: [
        { type: "Studio", count: 5, price: "1,300,000" },
        { type: "1 Bedroom", count: 7, price: "1,900,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Central Park Lofts",
      developer: "Modern Living Developers",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "101 5th Ave, Manhattan, NY",
      walkingTime: "2",
      isPopular: true,
      isCompleted: false,
      amenities: [
        "Private rooftop terraces",
        "Gym with personal trainers",
        "Luxury spa treatments",
        "High-speed elevators",
        "On-site wine bar",
        "Concierge for residents",
        "Soundproof music rooms",
        "Exclusive shopping access",
      ],
      layouts: [
        { type: "Loft", count: 4, price: "3,100,000" },
        { type: "2 Bedrooms", count: 6, price: "4,500,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Lakeside Villas",
      developer: "Tranquil Living",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "654 Serenity Ln, South Lake Tahoe, CA",
      walkingTime: "7",
      isPopular: false,
      isCompleted: true,
      amenities: [
        "Private docks",
        "Lakeside views",
        "Gourmet kitchens",
        "Fire pits",
        "Outdoor kitchens",
        "Jacuzzis",
        "Home automation",
        "Security systems",
      ],
      layouts: [
        { type: "2 Bedrooms", count: 10, price: "2,200,000" },
        { type: "3 Bedrooms", count: 5, price: "3,100,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Countryside Manor",
      developer: "Heritage Homes",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "987 Country Rd, Nashville, TN",
      walkingTime: "15",
      isPopular: false,
      isCompleted: false,
      amenities: [
        "Horse stables",
        "Private gardens",
        "Gated entry",
        "Chef's kitchen",
        "Wine cellar",
        "Library",
        "Home office",
        "Outdoor pool",
      ],
      layouts: [
        { type: "4 Bedrooms", count: 3, price: "3,500,000" },
        { type: "5 Bedrooms", count: 2, price: "4,700,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Seaside Escape",
      developer: "Coastal Builders",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "123 Ocean Drive, Miami Beach, FL",
      walkingTime: "2",
      isPopular: true,
      isCompleted: true,
      amenities: [
        "Horse stables",
        "Private gardens",
        "Gated entry",
        "Chef's kitchen",
        "Wine cellar",
        "Library",
        "Home office",
        "Outdoor pool",
      ],
      layouts: [
        { type: "4 Bedrooms", count: 3, price: "3,500,000" },
        { type: "5 Bedrooms", count: 2, price: "4,700,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Sky Tower",
      developer: "Metropolitan Properties",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "789 Market St, San Francisco, CA",
      walkingTime: "5",
      isPopular: true,
      isCompleted: false,
      amenities: [
        "Rooftop infinity pool",
        "24/7 concierge",
        "Luxury spa",
        "Movie theater",
        "Private lounges",
        "Gourmet dining options",
        "Pet-friendly facilities",
        "Smart home automation",
      ],
      layouts: [
        { type: "Studio", count: 4, price: "1,500,000" },
        { type: "1 Bedroom", count: 10, price: "2,100,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/136407/pexels-photo-136407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Palm Grove Residences",
      developer: "Sunset Developers",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "567 Sunset Blvd, Los Angeles, CA",
      walkingTime: "3",
      isPopular: true,
      isCompleted: true,
      amenities: [
        "Private rooftop gardens",
        "Resort-style pool",
        "Full-service gym",
        "High-speed internet",
        "Pet park",
        "Personalized butler service",
        "Exclusive residents' club",
        "State-of-the-art security",
      ],
      layouts: [
        { type: "1 Bedroom", count: 8, price: "2,300,000" },
        { type: "2 Bedrooms", count: 6, price: "3,200,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/208736/pexels-photo-208736.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Evergreen Towers",
      developer: "Green Living Estates",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "222 Pine St, Seattle, WA",
      walkingTime: "4",
      isPopular: false,
      isCompleted: true,
      amenities: [
        "Eco-friendly design",
        "Solar energy solutions",
        "Community garden",
        "Yoga & meditation rooms",
        "Private balconies",
        "On-site co-working space",
        "EV charging stations",
        "Luxury clubhouse",
      ],
      layouts: [
        { type: "Studio", count: 5, price: "1,300,000" },
        { type: "1 Bedroom", count: 7, price: "1,900,000" },
      ],
    },
    {
      image:
        "https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      title: "Central Park Lofts",
      developer: "Modern Living Developers",
      price: "From 3 750 000",
      description: "2 bed, 1 bath, 1,000 sq ft",
      rating: 4.5,
      location: "Beachfront",
  
      address: "101 5th Ave, Manhattan, NY",
      walkingTime: "2",
      isPopular: true,
      isCompleted: false,
      amenities: [
        "Private rooftop terraces",
        "Gym with personal trainers",
        "Luxury spa treatments",
        "High-speed elevators",
        "On-site wine bar",
        "Concierge for residents",
        "Soundproof music rooms",
        "Exclusive shopping access",
      ],
      layouts: [
        { type: "Loft", count: 4, price: "3,100,000" },
        { type: "2 Bedrooms", count: 6, price: "4,500,000" },
      ],
    },
  ];
  

//  mock data for layouts
export const layouts = [
    {
      id: "layout-1",
      type: "2 Bedrooms",
      area: 810.00,
      areaUnit: "ft²",
      building: "Tower A",
      floor: "15",
      unitNumber: "1502",
      price: 4521807,
      currency: "د.إ",
      projectName: "Lucent33",
      developer: "ZD Jasper Realty",
      floorPlanImage: "layout1.png",
      status: "Completed",
      rooms: {
        bedrooms: 2,
        bathrooms: 2
      },
      isAvailable: true,
      lastUpdated: "2024-02-14",
      features: [
        "Open Kitchen",
        "Balcony",
        "Maid's Room"
      ]
    },
    {
      id: "layout-2",
      type: "3 Bedrooms",
      area: 1200.00,
      areaUnit: "ft²",
      building: "Tower B",
      floor: "20",
      unitNumber: "2001",
      price: 6750000,
      currency: "د.إ",
      projectName: "Lucent33",
      developer: "ZD Jasper Realty",
      floorPlanImage: "layout2.png",
      status: "Available",
      rooms: {
        bedrooms: 3,
        bathrooms: 3
      },
      isAvailable: true,
      lastUpdated: "2024-02-14",
      features: [
        "Open Kitchen",
        "Balcony",
        "Study Room",
        "Maid's Room"
      ]
    },
    {
      id: "layout-3",
      type: "1 Bedroom",
      area: 650.00,
      areaUnit: "ft²",
      building: "Tower A",
      floor: "10",
      unitNumber: "1003",
      price: 2850000,
      currency: "د.إ",
      projectName: "Lucent33",
      developer: "ZD Jasper Realty",
      floorPlanImage: "layout3.png",
      status: "Completed",
      rooms: {
        bedrooms: 1,
        bathrooms: 1.5
      },
      isAvailable: true,
      lastUpdated: "2024-02-14",
      features: [
        "Open Kitchen",
        "Balcony"
      ]
    },
    {
      id: "layout-4",
      type: "Studio",
      area: 450.00,
      areaUnit: "ft²",
      building: "Tower C",
      floor: "5",
      unitNumber: "504",
      price: 1950000,
      currency: "د.إ",
      projectName: "Lucent33",
      developer: "ZD Jasper Realty",
      floorPlanImage: "layout4.png",
      status: "Sold",
      rooms: {
        bedrooms: 0,
        bathrooms: 1
      },
      isAvailable: false,
      lastUpdated: "2024-02-14",
      features: [
        "Open Kitchen",
        "City View"
      ]
    },
    {
      id: "layout-5",
      type: "4 Bedrooms",
      area: 2100.00,
      areaUnit: "ft²",
      building: "Tower B",
      floor: "25",
      unitNumber: "2501",
      price: 8900000,
      currency: "د.إ",
      projectName: "Lucent33",
      developer: "ZD Jasper Realty",
      floorPlanImage: "layout1.png",
      status: "Available",
      rooms: {
        bedrooms: 4,
        bathrooms: 4.5
      },
      isAvailable: true,
      lastUpdated: "2024-02-14",
      features: [
        "Open Kitchen",
        "Balcony",
        "Maid's Room",
        "Study Room",
        "Private Pool"
      ]
    },
    {
      id: "layout-6",
      type: "2 Bedrooms",
      area: 950.00,
      areaUnit: "ft²",
      building: "Tower D",
      floor: "12",
      unitNumber: "1205",
      price: 4980000,
      currency: "د.إ",
      projectName: "Lucent33",
      developer: "ZD Jasper Realty",
      floorPlanImage: "layout2.png",
      status: "Reserved",
      rooms: {
        bedrooms: 2,
        bathrooms: 2.5
      },
      isAvailable: false,
      lastUpdated: "2024-02-14",
      features: [
        "Open Kitchen",
        "Balcony",
        "Study Nook"
      ]
    },
    {
      id: "layout-7",
      type: "3 Bedrooms",
      area: 1450.00,
      areaUnit: "ft²",
      building: "Tower C",
      floor: "18",
      unitNumber: "1802",
      price: 7200000,
      currency: "د.إ",
      projectName: "Lucent33",
      developer: "ZD Jasper Realty",
      floorPlanImage: "layout3.png",
      status: "Completed",
      rooms: {
        bedrooms: 3,
        bathrooms: 3.5
      },
      isAvailable: true,
      lastUpdated: "2024-02-14",
      features: [
        "Open Kitchen",
        "Dual Balcony",
        "Maid's Room",
        "Storage Room"
      ]
    },
    {
      id: "layout-8",
      type: "Penthouse",
      area: 3200.00,
      areaUnit: "ft²",
      building: "Tower A",
      floor: "30",
      unitNumber: "PH01",
      price: 15800000,
      currency: "د.إ",
      projectName: "Lucent33",
      developer: "ZD Jasper Realty",
      floorPlanImage: "layout4.png",
      status: "Available",
      rooms: {
        bedrooms: 5,
        bathrooms: 5.5
      },
      isAvailable: true,
      lastUpdated: "2024-02-14",
      features: [
        "Open Kitchen",
        "Wraparound Balcony",
        "Maid's Room",
        "Study Room",
        "Private Pool",
        "Private Elevator"
      ]
    },
    {
      id: "layout-9",
      type: "1 Bedroom",
      area: 750.00,
      areaUnit: "ft²",
      building: "Tower D",
      floor: "8",
      unitNumber: "805",
      price: 3250000,
      currency: "د.إ",
      projectName: "Lucent33",
      developer: "ZD Jasper Realty",
      floorPlanImage: "layout1.png",
      status: "Completed",
      rooms: {
        bedrooms: 1,
        bathrooms: 2
      },
      isAvailable: true,
      lastUpdated: "2024-02-14",
      features: [
        "Open Kitchen",
        "Large Balcony",
        "Study Nook"
      ]
    },
    {
      id: "layout-10",
      type: "2 Bedrooms + Study",
      area: 1100.00,
      areaUnit: "ft²",
      building: "Tower B",
      floor: "22",
      unitNumber: "2204",
      price: 5650000,
      currency: "د.إ",
      projectName: "Lucent33",
      developer: "ZD Jasper Realty",
      floorPlanImage: "layout2.png",
      status: "Available",
      rooms: {
        bedrooms: 2,
        bathrooms: 2.5
      },
      isAvailable: true,
      lastUpdated: "2024-02-14",
      features: [
        "Open Kitchen",
        "Dual Balcony",
        "Study Room",
        "Storage Room"
      ]
    },
    {
      id: "layout-7",
      type: "3 Bedrooms",
      area: 1450.00,
      areaUnit: "ft²",
      building: "Tower C",
      floor: "18",
      unitNumber: "1802",
      price: 7200000,
      currency: "د.إ",
      projectName: "Lucent33",
      developer: "ZD Jasper Realty",
      floorPlanImage: "layout3.png",
      status: "Completed",
      rooms: {
        bedrooms: 3,
        bathrooms: 3.5
      },
      isAvailable: true,
      lastUpdated: "2024-02-14",
      features: [
        "Open Kitchen",
        "Dual Balcony",
        "Maid's Room",
        "Storage Room"
      ]
    },
    {
      id: "layout-7",
      type: "3 Bedrooms",
      area: 1450.00,
      areaUnit: "ft²",
      building: "Tower C",
      floor: "18",
      unitNumber: "1802",
      price: 7200000,
      currency: "د.إ",
      projectName: "Lucent33",
      developer: "ZD Jasper Realty",
      floorPlanImage: "layout3.png",
      status: "Completed",
      rooms: {
        bedrooms: 3,
        bathrooms: 3.5
      },
      isAvailable: true,
      lastUpdated: "2024-02-14",
      features: [
        "Open Kitchen",
        "Dual Balcony",
        "Maid's Room",
        "Storage Room"
      ]
    },
    {
      id: "layout-7",
      type: "3 Bedrooms",
      area: 1450.00,
      areaUnit: "ft²",
      building: "Tower C",
      floor: "18",
      unitNumber: "1802",
      price: 7200000,
      currency: "د.إ",
      projectName: "Lucent33",
      developer: "ZD Jasper Realty",
      floorPlanImage: "layout3.png",
      status: "Completed",
      rooms: {
        bedrooms: 3,
        bathrooms: 3.5
      },
      isAvailable: true,
      lastUpdated: "2024-02-14",
      features: [
        "Open Kitchen",
        "Dual Balcony",
        "Maid's Room",
        "Storage Room"
      ]
    },
    {
      id: "layout-7",
      type: "3 Bedrooms",
      area: 1450.00,
      areaUnit: "ft²",
      building: "Tower C",
      floor: "18",
      unitNumber: "1802",
      price: 7200000,
      currency: "د.إ",
      projectName: "Lucent33",
      developer: "ZD Jasper Realty",
      floorPlanImage: "layout3.png",
      status: "Completed",
      rooms: {
        bedrooms: 3,
        bathrooms: 3.5
      },
      isAvailable: true,
      lastUpdated: "2024-02-14",
      features: [
        "Open Kitchen",
        "Dual Balcony",
        "Maid's Room",
        "Storage Room"
      ]
    },
    {
      id: "layout-7",
      type: "3 Bedrooms",
      area: 1450.00,
      areaUnit: "ft²",
      building: "Tower C",
      floor: "18",
      unitNumber: "1802",
      price: 7200000,
      currency: "د.إ",
      projectName: "Lucent33",
      developer: "ZD Jasper Realty",
      floorPlanImage: "layout3.png",
      status: "Completed",
      rooms: {
        bedrooms: 3,
        bathrooms: 3.5
      },
      isAvailable: true,
      lastUpdated: "2024-02-14",
      features: [
        "Open Kitchen",
        "Dual Balcony",
        "Maid's Room",
        "Storage Room"
      ]
    }
    
  ];