// mockdata for property cards

export const cards = [
  {
    image: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Skyline Heights',
    developer: 'Urban Edge Properties',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '123 Liberty St, New York, NY',
    walkingTime: '5',
    isPopular: true,
    isCompleted: true,
    amenities: [
      'Rooftop garden',
      '24/7 security',
      'Fitness center',
      'Co-working space',
      'Indoor pool',
      'Pet-friendly',
      'Concierge service',
      'Private theater'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-26548'
  },
  {
    image: 'https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Oceanview Residences',
    developer: 'Seaside Developments',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '456 Ocean Ave, Santa Monica, CA',
    walkingTime: '2',
    isPopular: true,
    isCompleted: false,
    amenities: [
      'Beach access',
      'Infinity pool',
      'Spa and wellness center',
      'Gourmet dining',
      'Yoga studio',
      'Valet parking',
      'Private balconies',
      'Smart home technology'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-37635'
  },
  {
    image: 'https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Mountain Retreat',
    developer: 'Highland Estates',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '789 Alpine Rd, Aspen, CO',
    walkingTime: '10',
    isPopular: false,
    isCompleted: true,
    amenities: [
      'Ski-in/ski-out access',
      'Heated floors',
      'Fireplace lounges',
      'Private hot tubs',
      'Gourmet kitchens',
      'Wine cellars',
      'Home theaters',
      'Game rooms'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-44356'
  },
  {
    image: 'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Urban Oasis',
    developer: 'Cityscape Builders',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '321 Wacker Dr, Chicago, IL',
    walkingTime: '3',
    isPopular: true,
    isCompleted: false,
    amenities: [
      'Sky lounge',
      'Fitness center',
      'Indoor pool',
      'Business center',
      'Pet spa',
      'Outdoor terrace',
      'Bike storage',
      'On-site retail'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-29196'
  },
  {
    image: 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Lakeside Villas',
    developer: 'Tranquil Living',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '654 Serenity Ln, South Lake Tahoe, CA',
    walkingTime: '7',
    isPopular: false,
    isCompleted: true,
    amenities: [
      'Private docks',
      'Lakeside views',
      'Gourmet kitchens',
      'Fire pits',
      'Outdoor kitchens',
      'Jacuzzis',
      'Home automation',
      'Security systems'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-74962'
  },
  {
    image: 'https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Countryside Manor',
    developer: 'Heritage Homes',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '987 Country Rd, Nashville, TN',
    walkingTime: '15',
    isPopular: false,
    isCompleted: false,
    amenities: [
      'Horse stables',
      'Private gardens',
      'Gated entry',
      "Chef's kitchen",
      'Wine cellar',
      'Library',
      'Home office',
      'Outdoor pool'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-17999'
  },
  {
    image: 'https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Seaside Escape',
    developer: 'Coastal Builders',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '123 Ocean Drive, Miami Beach, FL',
    walkingTime: '2',
    isPopular: true,
    isCompleted: true,
    amenities: [
      'Horse stables',
      'Private gardens',
      'Gated entry',
      "Chef's kitchen",
      'Wine cellar',
      'Library',
      'Home office',
      'Outdoor pool'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-40212'
  },
  {
    image: 'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Sky Tower',
    developer: 'Metropolitan Properties',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '789 Market St, San Francisco, CA',
    walkingTime: '5',
    isPopular: true,
    isCompleted: false,
    amenities: [
      'Rooftop infinity pool',
      '24/7 concierge',
      'Luxury spa',
      'Movie theater',
      'Private lounges',
      'Gourmet dining options',
      'Pet-friendly facilities',
      'Smart home automation'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-43607'
  },
  {
    image: 'https://images.pexels.com/photos/136407/pexels-photo-136407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Palm Grove Residences',
    developer: 'Sunset Developers',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '567 Sunset Blvd, Los Angeles, CA',
    walkingTime: '3',
    isPopular: true,
    isCompleted: true,
    amenities: [
      'Private rooftop gardens',
      'Resort-style pool',
      'Full-service gym',
      'High-speed internet',
      'Pet park',
      'Personalized butler service',
      "Exclusive residents' club",
      'State-of-the-art security'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-84717'
  },
  {
    image: 'https://images.pexels.com/photos/208736/pexels-photo-208736.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Evergreen Towers',
    developer: 'Green Living Estates',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '222 Pine St, Seattle, WA',
    walkingTime: '4',
    isPopular: false,
    isCompleted: true,
    amenities: [
      'Eco-friendly design',
      'Solar energy solutions',
      'Community garden',
      'Yoga & meditation rooms',
      'Private balconies',
      'On-site co-working space',
      'EV charging stations',
      'Luxury clubhouse'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-29684'
  },
  {
    image: 'https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Central Park Lofts',
    developer: 'Modern Living Developers',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '101 5th Ave, Manhattan, NY',
    walkingTime: '2',
    isPopular: true,
    isCompleted: false,
    amenities: [
      'Private rooftop terraces',
      'Gym with personal trainers',
      'Luxury spa treatments',
      'High-speed elevators',
      'On-site wine bar',
      'Concierge for residents',
      'Soundproof music rooms',
      'Exclusive shopping access'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-97237'
  },
  {
    image: 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Lakeside Villas',
    developer: 'Tranquil Living',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '654 Serenity Ln, South Lake Tahoe, CA',
    walkingTime: '7',
    isPopular: false,
    isCompleted: true,
    amenities: [
      'Private docks',
      'Lakeside views',
      'Gourmet kitchens',
      'Fire pits',
      'Outdoor kitchens',
      'Jacuzzis',
      'Home automation',
      'Security systems'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-12642'
  },
  {
    image: 'https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Countryside Manor',
    developer: 'Heritage Homes',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '987 Country Rd, Nashville, TN',
    walkingTime: '15',
    isPopular: false,
    isCompleted: false,
    amenities: [
      'Horse stables',
      'Private gardens',
      'Gated entry',
      "Chef's kitchen",
      'Wine cellar',
      'Library',
      'Home office',
      'Outdoor pool'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-2429'
  },
  {
    image: 'https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Seaside Escape',
    developer: 'Coastal Builders',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '123 Ocean Drive, Miami Beach, FL',
    walkingTime: '2',
    isPopular: true,
    isCompleted: true,
    amenities: [
      'Horse stables',
      'Private gardens',
      'Gated entry',
      "Chef's kitchen",
      'Wine cellar',
      'Library',
      'Home office',
      'Outdoor pool'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-54166'
  },
  {
    image: 'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Sky Tower',
    developer: 'Metropolitan Properties',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '789 Market St, San Francisco, CA',
    walkingTime: '5',
    isPopular: true,
    isCompleted: false,
    amenities: [
      'Rooftop infinity pool',
      '24/7 concierge',
      'Luxury spa',
      'Movie theater',
      'Private lounges',
      'Gourmet dining options',
      'Pet-friendly facilities',
      'Smart home automation'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-77305'
  },
  {
    image: 'https://images.pexels.com/photos/136407/pexels-photo-136407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Palm Grove Residences',
    developer: 'Sunset Developers',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '567 Sunset Blvd, Los Angeles, CA',
    walkingTime: '3',
    isPopular: true,
    isCompleted: true,
    amenities: [
      'Private rooftop gardens',
      'Resort-style pool',
      'Full-service gym',
      'High-speed internet',
      'Pet park',
      'Personalized butler service',
      "Exclusive residents' club",
      'State-of-the-art security'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-34700'
  },
  {
    image: 'https://images.pexels.com/photos/208736/pexels-photo-208736.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Evergreen Towers',
    developer: 'Green Living Estates',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '222 Pine St, Seattle, WA',
    walkingTime: '4',
    isPopular: false,
    isCompleted: true,
    amenities: [
      'Eco-friendly design',
      'Solar energy solutions',
      'Community garden',
      'Yoga & meditation rooms',
      'Private balconies',
      'On-site co-working space',
      'EV charging stations',
      'Luxury clubhouse'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-74248'
  },
  {
    image: 'https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Central Park Lofts',
    developer: 'Modern Living Developers',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '101 5th Ave, Manhattan, NY',
    walkingTime: '2',
    isPopular: true,
    isCompleted: false,
    amenities: [
      'Private rooftop terraces',
      'Gym with personal trainers',
      'Luxury spa treatments',
      'High-speed elevators',
      'On-site wine bar',
      'Concierge for residents',
      'Soundproof music rooms',
      'Exclusive shopping access'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-64851'
  },
  {
    image: 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Lakeside Villas',
    developer: 'Tranquil Living',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '654 Serenity Ln, South Lake Tahoe, CA',
    walkingTime: '7',
    isPopular: false,
    isCompleted: true,
    amenities: [
      'Private docks',
      'Lakeside views',
      'Gourmet kitchens',
      'Fire pits',
      'Outdoor kitchens',
      'Jacuzzis',
      'Home automation',
      'Security systems'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-48255'
  },
  {
    image: 'https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Countryside Manor',
    developer: 'Heritage Homes',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '987 Country Rd, Nashville, TN',
    walkingTime: '15',
    isPopular: false,
    isCompleted: false,
    amenities: [
      'Horse stables',
      'Private gardens',
      'Gated entry',
      "Chef's kitchen",
      'Wine cellar',
      'Library',
      'Home office',
      'Outdoor pool'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-20120'
  },
  {
    image: 'https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Seaside Escape',
    developer: 'Coastal Builders',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '123 Ocean Drive, Miami Beach, FL',
    walkingTime: '2',
    isPopular: true,
    isCompleted: true,
    amenities: [
      'Horse stables',
      'Private gardens',
      'Gated entry',
      "Chef's kitchen",
      'Wine cellar',
      'Library',
      'Home office',
      'Outdoor pool'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-74558'
  },
  {
    image: 'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Sky Tower',
    developer: 'Metropolitan Properties',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '789 Market St, San Francisco, CA',
    walkingTime: '5',
    isPopular: true,
    isCompleted: false,
    amenities: [
      'Rooftop infinity pool',
      '24/7 concierge',
      'Luxury spa',
      'Movie theater',
      'Private lounges',
      'Gourmet dining options',
      'Pet-friendly facilities',
      'Smart home automation'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-6484'
  },
  {
    image: 'https://images.pexels.com/photos/136407/pexels-photo-136407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Palm Grove Residences',
    developer: 'Sunset Developers',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '567 Sunset Blvd, Los Angeles, CA',
    walkingTime: '3',
    isPopular: true,
    isCompleted: true,
    amenities: [
      'Private rooftop gardens',
      'Resort-style pool',
      'Full-service gym',
      'High-speed internet',
      'Pet park',
      'Personalized butler service',
      "Exclusive residents' club",
      'State-of-the-art security'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-77213'
  },
  {
    image: 'https://images.pexels.com/photos/208736/pexels-photo-208736.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Evergreen Towers',
    developer: 'Green Living Estates',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '222 Pine St, Seattle, WA',
    walkingTime: '4',
    isPopular: false,
    isCompleted: true,
    amenities: [
      'Eco-friendly design',
      'Solar energy solutions',
      'Community garden',
      'Yoga & meditation rooms',
      'Private balconies',
      'On-site co-working space',
      'EV charging stations',
      'Luxury clubhouse'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-69539'
  },
  {
    image: 'https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Central Park Lofts',
    developer: 'Modern Living Developers',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '101 5th Ave, Manhattan, NY',
    walkingTime: '2',
    isPopular: true,
    isCompleted: false,
    amenities: [
      'Private rooftop terraces',
      'Gym with personal trainers',
      'Luxury spa treatments',
      'High-speed elevators',
      'On-site wine bar',
      'Concierge for residents',
      'Soundproof music rooms',
      'Exclusive shopping access'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-40591'
  },
  {
    image: 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Lakeside Villas',
    developer: 'Tranquil Living',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '654 Serenity Ln, South Lake Tahoe, CA',
    walkingTime: '7',
    isPopular: false,
    isCompleted: true,
    amenities: [
      'Private docks',
      'Lakeside views',
      'Gourmet kitchens',
      'Fire pits',
      'Outdoor kitchens',
      'Jacuzzis',
      'Home automation',
      'Security systems'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-4279'
  },
  {
    image: 'https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Countryside Manor',
    developer: 'Heritage Homes',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '987 Country Rd, Nashville, TN',
    walkingTime: '15',
    isPopular: false,
    isCompleted: false,
    amenities: [
      'Horse stables',
      'Private gardens',
      'Gated entry',
      "Chef's kitchen",
      'Wine cellar',
      'Library',
      'Home office',
      'Outdoor pool'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-42308'
  },
  {
    image: 'https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Seaside Escape',
    developer: 'Coastal Builders',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '123 Ocean Drive, Miami Beach, FL',
    walkingTime: '2',
    isPopular: true,
    isCompleted: true,
    amenities: [
      'Horse stables',
      'Private gardens',
      'Gated entry',
      "Chef's kitchen",
      'Wine cellar',
      'Library',
      'Home office',
      'Outdoor pool'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-50218'
  },
  {
    image: 'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Sky Tower',
    developer: 'Metropolitan Properties',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '789 Market St, San Francisco, CA',
    walkingTime: '5',
    isPopular: true,
    isCompleted: false,
    amenities: [
      'Rooftop infinity pool',
      '24/7 concierge',
      'Luxury spa',
      'Movie theater',
      'Private lounges',
      'Gourmet dining options',
      'Pet-friendly facilities',
      'Smart home automation'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-49529'
  },
  {
    image: 'https://images.pexels.com/photos/136407/pexels-photo-136407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Palm Grove Residences',
    developer: 'Sunset Developers',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '567 Sunset Blvd, Los Angeles, CA',
    walkingTime: '3',
    isPopular: true,
    isCompleted: true,
    amenities: [
      'Private rooftop gardens',
      'Resort-style pool',
      'Full-service gym',
      'High-speed internet',
      'Pet park',
      'Personalized butler service',
      "Exclusive residents' club",
      'State-of-the-art security'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-74057'
  },
  {
    image: 'https://images.pexels.com/photos/208736/pexels-photo-208736.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Evergreen Towers',
    developer: 'Green Living Estates',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '222 Pine St, Seattle, WA',
    walkingTime: '4',
    isPopular: false,
    isCompleted: true,
    amenities: [
      'Eco-friendly design',
      'Solar energy solutions',
      'Community garden',
      'Yoga & meditation rooms',
      'Private balconies',
      'On-site co-working space',
      'EV charging stations',
      'Luxury clubhouse'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-4701'
  },
  {
    image: 'https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    title: 'Central Park Lofts',
    developer: 'Modern Living Developers',
    price: 'From 3 750 000',
    description: '2 bed, 1 bath, 1,000 sq ft',
    rating: 4.5,
    location: 'Beachfront',
    address: '101 5th Ave, Manhattan, NY',
    walkingTime: '2',
    isPopular: true,
    isCompleted: false,
    amenities: [
      'Private rooftop terraces',
      'Gym with personal trainers',
      'Luxury spa treatments',
      'High-speed elevators',
      'On-site wine bar',
      'Concierge for residents',
      'Soundproof music rooms',
      'Exclusive shopping access'
    ],
    layouts: [ [Object], [Object] ],
    id: '1740391654985-80310'
  }
]

//  mock data for layouts
export const layouts = [
  {
    id: "layout-1",
    type: "2 Bedrooms",
    area: 810.0,
    areaUnit: "ft²",
    building: "Tower A",
    floor: "15",
    unitNumber: "1502",
    price: 4521807,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout1.png",
    status: "Completed",
    rooms: {
      bedrooms: 2,
      bathrooms: 2,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Balcony", "Maid's Room"],
  },
  {
    id: "layout-2",
    type: "3 Bedrooms",
    area: 1200.0,
    areaUnit: "ft²",
    building: "Tower B",
    floor: "20",
    unitNumber: "2001",
    price: 6750000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout2.png",
    status: "Available",
    rooms: {
      bedrooms: 3,
      bathrooms: 3,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Balcony", "Study Room", "Maid's Room"],
  },
  {
    id: "layout-3",
    type: "1 Bedroom",
    area: 650.0,
    areaUnit: "ft²",
    building: "Tower A",
    floor: "10",
    unitNumber: "1003",
    price: 2850000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout3.png",
    status: "Completed",
    rooms: {
      bedrooms: 1,
      bathrooms: 1.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Balcony"],
  },
  {
    id: "layout-4",
    type: "Studio",
    area: 450.0,
    areaUnit: "ft²",
    building: "Tower C",
    floor: "5",
    unitNumber: "504",
    price: 1950000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout4.png",
    status: "Sold",
    rooms: {
      bedrooms: 0,
      bathrooms: 1,
    },
    isAvailable: false,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "City View"],
  },
  {
    id: "layout-5",
    type: "4 Bedrooms",
    area: 2100.0,
    areaUnit: "ft²",
    building: "Tower B",
    floor: "25",
    unitNumber: "2501",
    price: 8900000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout1.png",
    status: "Available",
    rooms: {
      bedrooms: 4,
      bathrooms: 4.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: [
      "Open Kitchen",
      "Balcony",
      "Maid's Room",
      "Study Room",
      "Private Pool",
    ],
  },
  {
    id: "layout-6",
    type: "2 Bedrooms",
    area: 950.0,
    areaUnit: "ft²",
    building: "Tower D",
    floor: "12",
    unitNumber: "1205",
    price: 4980000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout2.png",
    status: "Reserved",
    rooms: {
      bedrooms: 2,
      bathrooms: 2.5,
    },
    isAvailable: false,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Balcony", "Study Nook"],
  },
  {
    id: "layout-7",
    type: "3 Bedrooms",
    area: 1450.0,
    areaUnit: "ft²",
    building: "Tower C",
    floor: "18",
    unitNumber: "1802",
    price: 7200000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout3.png",
    status: "Completed",
    rooms: {
      bedrooms: 3,
      bathrooms: 3.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Dual Balcony", "Maid's Room", "Storage Room"],
  },
  {
    id: "layout-8",
    type: "Penthouse",
    area: 3200.0,
    areaUnit: "ft²",
    building: "Tower A",
    floor: "30",
    unitNumber: "PH01",
    price: 15800000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout4.png",
    status: "Available",
    rooms: {
      bedrooms: 5,
      bathrooms: 5.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: [
      "Open Kitchen",
      "Wraparound Balcony",
      "Maid's Room",
      "Study Room",
      "Private Pool",
      "Private Elevator",
    ],
  },
  {
    id: "layout-9",
    type: "1 Bedroom",
    area: 750.0,
    areaUnit: "ft²",
    building: "Tower D",
    floor: "8",
    unitNumber: "805",
    price: 3250000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout1.png",
    status: "Completed",
    rooms: {
      bedrooms: 1,
      bathrooms: 2,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Large Balcony", "Study Nook"],
  },
  {
    id: "layout-10",
    type: "2 Bedrooms + Study",
    area: 1100.0,
    areaUnit: "ft²",
    building: "Tower B",
    floor: "22",
    unitNumber: "2204",
    price: 5650000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout2.png",
    status: "Available",
    rooms: {
      bedrooms: 2,
      bathrooms: 2.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Dual Balcony", "Study Room", "Storage Room"],
  },
  {
    id: "layout-7",
    type: "3 Bedrooms",
    area: 1450.0,
    areaUnit: "ft²",
    building: "Tower C",
    floor: "18",
    unitNumber: "1802",
    price: 7200000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout3.png",
    status: "Completed",
    rooms: {
      bedrooms: 3,
      bathrooms: 3.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Dual Balcony", "Maid's Room", "Storage Room"],
  },
  {
    id: "layout-7",
    type: "3 Bedrooms",
    area: 1450.0,
    areaUnit: "ft²",
    building: "Tower C",
    floor: "18",
    unitNumber: "1802",
    price: 7200000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout3.png",
    status: "Completed",
    rooms: {
      bedrooms: 3,
      bathrooms: 3.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Dual Balcony", "Maid's Room", "Storage Room"],
  },
  {
    id: "layout-7",
    type: "3 Bedrooms",
    area: 1450.0,
    areaUnit: "ft²",
    building: "Tower C",
    floor: "18",
    unitNumber: "1802",
    price: 7200000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout3.png",
    status: "Completed",
    rooms: {
      bedrooms: 3,
      bathrooms: 3.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Dual Balcony", "Maid's Room", "Storage Room"],
  },
  {
    id: "layout-7",
    type: "3 Bedrooms",
    area: 1450.0,
    areaUnit: "ft²",
    building: "Tower C",
    floor: "18",
    unitNumber: "1802",
    price: 7200000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout3.png",
    status: "Completed",
    rooms: {
      bedrooms: 3,
      bathrooms: 3.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Dual Balcony", "Maid's Room", "Storage Room"],
  },
  {
    id: "layout-7",
    type: "3 Bedrooms",
    area: 1450.0,
    areaUnit: "ft²",
    building: "Tower C",
    floor: "18",
    unitNumber: "1802",
    price: 7200000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout3.png",
    status: "Completed",
    rooms: {
      bedrooms: 3,
      bathrooms: 3.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Dual Balcony", "Maid's Room", "Storage Room"],
  },
];

export const courses = [
  {
    id: 1,
    name: "Advanced Web Development",
    description: "Learn modern web development techniques and best practices",
    lectureCount: 24,
    source: "Bayut",
    tags: ["Web Development", "Frontend"],
  },
  {
    id: 2,
    name: "Data Science Fundamentals",
    description:
      "Explore data analysis, visualization, and machine learning concepts",
    lectureCount: 30,
    source: "Dubizzle",
    tags: [
      "Data Science",
      "Machine Learning",
      "Data Analysis",
      "Data Handling",
    ],
  },
  {
    id: 3,
    name: "Mobile App Development",
    description:
      "Build native and cross-platform mobile applications from scratch",
    lectureCount: 20,
    source: "BWC",
    tags: [
      "Mobile Development",
      "Cross-Platform",
      "App Development",
      "Frontend",
    ],
  },
  {
    id: 4,
    name: "Cybersecurity Essentials",
    description:
      "Understand key cybersecurity principles and practices to protect systems",
    lectureCount: 18,
    source: "Emaar",
    tags: [
      "Cybersecurity",
      "Security Principles",
      "System Protection",
      "Data Handling",
    ],
  },
  {
    id: 5,
    name: "Cloud Computing Mastery",
    description:
      "Dive into cloud infrastructure, deployment, and services management",
    lectureCount: 25,
    source: "Raheja",
    tags: ["Cloud Computing", "Cloud Infrastructure", "Deployment", "Services"],
  },
  {
    id: 6,
    name: "CRM Management",
    description:
      "Dive into CRM Management, customization, and services management",
    lectureCount: 25,
    source: "Raheja",
    tags: ["CRM", "Pipelines", "Services"],
  },
];

export const lessonsData = [
  {
    id: 1,
    sequence: 1,
    title: "Introduction to React Fundamentals",
    duration: "45 mins",
    type: "video",
    description:
    "Learn the core concepts of React and its component-based architecture",
    isLocked: false,
    completed: true,
  },
  {
    id: 2,
    sequence: 2,
    title: "State Management in React",
    duration: "55 mins",
    type: "video",
    description: "Deep dive into useState, useEffect and component lifecycle",
    isLocked: false,
    completed: true,
  },
  {
    id: 3,
    sequence: 3,
    title: "Props and Component Communication",
    duration: "40 mins",
    type: "video",
    description: "Understanding data flow between React components",
    isLocked: false,
    completed: false,
  },
  {
    id: 4,
    sequence: 4,
    title: "React Hooks in Detail",
    duration: "60 mins",
    type: "video",
    description: "Comprehensive guide to built-in React hooks",
    isLocked: false,
    completed: false,
  },
  {
    id: 5,
    sequence: 5,
    title: "Advanced State Management",
    duration: "50 mins",
    type: "video",
    description: "Context API, Redux, and other state management solutions",
    isLocked: true,
    completed: false,
  },
  {
    id: 6,
    sequence: 6,
    title: "React Router and Navigation",
    duration: "35 mins",
    type: "video",
    description: "Building multi-page applications with React Router",
    isLocked: true,
    completed: false,
  },
  {
    id: 7,
    sequence: 7,
    title: "Forms and User Input",
    duration: "45 mins",
    type: "video",
    description: "Handling forms, validation, and user input in React",
    isLocked: true,
    completed: false,
  },
  {
    id: 8,
    sequence: 8,
    title: "API Integration",
    duration: "55 mins",
    type: "video",
    description: "Working with REST APIs and handling async operations",
    isLocked: true,
    completed: false,
  },
  {
    id: 9,
    sequence: 9,
    title: "Performance Optimization",
    duration: "50 mins",
    type: "video",
    description: "Techniques to optimize React application performance",
    isLocked: true,
    completed: false,
  },
  {
    id: 10,
    sequence: 10,
    title: "Deployment and Best Practices",
    duration: "40 mins",
    type: "video",
    description: "Deploying React apps and following industry best practices",
    isLocked: true,
    completed: false,
  },
];

// Lead Mock Data

export const mockLeads = [
  {
    
    agent_name: "Alice Johnson",
    lead_name: "John Doe",
    status: "New Lead",
    channel: "whatsapp",
    source: "PF",
    amount: 1250000,
  },
  {
    agent_name: "Michael Smith",
    lead_name: "Sarah Lee",
    status: "Follow-up",
    channel: "mail",
    source: "dubizzle",
    amount: 3200000,
  },
  {
    agent_name: "Jessica Brown",
    lead_name: "David Kim",
    status: "Closed",
    channel: "call",
    source: "behomes",
    amount: 4500000,
  },
  {
    agent_name: "Robert Wilson",
    lead_name: "Emily Davis",
    status: "Junk",
    channel: "website",
    source: "bayut",
    amount: 700000,
  },
  {
    agent_name: "Emma Thompson",
    lead_name: "James White",
    status: "New Lead",
    channel: "other",
    source: "vortexweb",
    amount: 2800000,
  },
  {
    agent_name: "Daniel Martinez",
    lead_name: "Olivia Harris",
    status: "Follow-up",
    channel: "whatsapp",
    source: "dubizzle",
    amount: 5400000,
  },
  {
    agent_name: "Sophia Anderson",
    lead_name: "William Carter",
    status: "Closed",
    channel: "mail",
    source: "other",
    amount: 6300000,
  },
  {
    agent_name: "David Scott",
    lead_name: "Mia Robinson",
    status: "Junk",
    channel: "call",
    source: "behomes",
    amount: 850000,
  },
  {
    agent_name: "Olivia King",
    lead_name: "Ethan Adams",
    status: "New Lead",
    channel: "website",
    source: "PF",
    amount: 2150000,
  },
  {
    agent_name: "Lucas Walker",
    lead_name: "Ava Wright",
    status: "Follow-up",
    channel: "other",
    source: "bayut",
    amount: 4900000,
  },
  {
    agent_name: "David Scott",
    lead_name: "Liam Turner",
    status: "New Lead",
    channel: "whatsapp",
    source: "PF",
    amount: 1500000,
  },
  {
    agent_name: "Olivia King",
    lead_name: "Grace Mitchell",
    status: "Follow-up",
    channel: "mail",
    source: "dubizzle",
    amount: 3100000,
  },
  {
    agent_name: "Michael Smith",
    lead_name: "Benjamin Clark",
    status: "Closed",
    channel: "call",
    source: "behomes",
    amount: 4700000,
  },
  {
    agent_name: "Lucas Walker",
    lead_name: "Isabella Lewis",
    status: "Junk",
    channel: "website",
    source: "bayut",
    amount: 800000,
  },
  {
    agent_name: "David Scott",
    lead_name: "Charlotte Evans",
    status: "New Lead",
    channel: "other",
    source: "vortexweb",
    amount: 2900000,
  },
  {
    agent_name: "Olivia King",
    lead_name: "Mason Cooper",
    status: "Follow-up",
    channel: "whatsapp",
    source: "dubizzle",
    amount: 5200000,
  },
  {
    agent_name: "Michael Smith",
    lead_name: "Harper Rodriguez",
    status: "Closed",
    channel: "mail",
    source: "other",
    amount: 6400000,
  },
  {
    agent_name: "Lucas Walker",
    lead_name: "Sebastian Perez",
    status: "Junk",
    channel: "call",
    source: "behomes",
    amount: 950000,
  },
  {
    agent_name: "David Scott",
    lead_name: "Maya Harris",
    status: "New Lead",
    channel: "website",
    source: "PF",
    amount: 2300000,
  },
  {
    agent_name: "Olivia King",
    lead_name: "Jackson Robinson",
    status: "Follow-up",
    channel: "other",
    source: "bayut",
    amount: 4600000,
  },
  {
    agent_name: "Michael Smith",
    lead_name: "Amelia King",
    status: "Closed",
    channel: "whatsapp",
    source: "vortexweb",
    amount: 5000000,
  },
  {
    agent_name: "Lucas Walker",
    lead_name: "Evan Scott",
    status: "Junk",
    channel: "mail",
    source: "dubizzle",
    amount: 720000,
  },
  {
    agent_name: "David Scott",
    lead_name: "Lily Green",
    status: "New Lead",
    channel: "call",
    source: "behomes",
    amount: 3100000,
  },
  {
    agent_name: "Olivia King",
    lead_name: "Aiden Walker",
    status: "Follow-up",
    channel: "website",
    source: "bayut",
    amount: 5100000,
  },
  {
    agent_name: "Michael Smith",
    lead_name: "Zoe Turner",
    status: "Closed",
    channel: "other",
    source: "PF",
    amount: 6300000,
  },
  {
    agent_name: "Lucas Walker",
    lead_name: "Landon Perez",
    status: "Junk",
    channel: "whatsapp",
    source: "dubizzle",
    amount: 880000,
  },
  {
    agent_name: "David Scott",
    lead_name: "Eva Walker",
    status: "New Lead",
    channel: "mail",
    source: "vortexweb",
    amount: 2500000,
  },
  {
    agent_name: "Olivia King",
    lead_name: "Mila Evans",
    status: "Follow-up",
    channel: "call",
    source: "behomes",
    amount: 4300000,
  },
  {
    agent_name: "Michael Smith",
    lead_name: "Ava White",
    status: "Closed",
    channel: "website",
    source: "bayut",
    amount: 5500000,
  },
  {
    agent_name: "Lucas Walker",
    lead_name: "Isla Brooks",
    status: "Junk",
    channel: "other",
    source: "dubizzle",
    amount: 700000,
  },
  {
    agent_name: "David Scott",
    lead_name: "Kai Carter",
    status: "New Lead",
    channel: "whatsapp",
    source: "PF",
    amount: 3800000,
  },
  {
    agent_name: "Olivia King",
    lead_name: "Lucas Miller",
    status: "Follow-up",
    channel: "call",
    source: "vortexweb",
    amount: 6200000,
  },
  {
    agent_name: "Michael Smith",
    lead_name: "Nora Bailey",
    status: "Closed",
    channel: "other",
    source: "dubizzle",
    amount: 5600000,
  },
  {
    agent_name: "Lucas Walker",
    lead_name: "Leo Carter",
    status: "Junk",
    channel: "website",
    source: "behomes",
    amount: 750000,
  },
  {
    agent_name: "David Scott",
    lead_name: "Scarlett Brown",
    status: "New Lead",
    channel: "mail",
    source: "bayut",
    amount: 2700000,
  },
  {
    agent_name: "Olivia King",
    lead_name: "Benjamin Harris",
    status: "Follow-up",
    channel: "other",
    source: "PF",
    amount: 4500000,
  },
  {
    agent_name: "Michael Smith",
    lead_name: "Eleanor Garcia",
    status: "Closed",
    channel: "call",
    source: "behomes",
    amount: 6800000,
  },
  {
    agent_name: "Lucas Walker",
    lead_name: "Oliver Scott",
    status: "Junk",
    channel: "whatsapp",
    source: "dubizzle",
    amount: 920000,
  },
  {
    agent_name: "David Scott",
    lead_name: "Ella Davis",
    status: "New Lead",
    channel: "website",
    source: "vortexweb",
    amount: 2200000,
  },
  {
    agent_name: "Olivia King",
    lead_name: "Jacob Wilson",
    status: "Follow-up",
    channel: "mail",
    source: "bayut",
    amount: 5300000,
  },
  {
    agent_name: "Michael Smith",
    lead_name: "Chloe Mitchell",
    status: "Closed",
    channel: "other",
    source: "PF",
    amount: 7400000,
  },
  {
    agent_name: "Lucas Walker",
    lead_name: "Grace Harris",
    status: "Junk",
    channel: "call",
    source: "dubizzle",
    amount: 650000,
  },
  {
    agent_name: "David Scott",
    lead_name: "Samuel Lee",
    status: "New Lead",
    channel: "other",
    source: "behomes",
    amount: 3100000,
  },
  {
    agent_name: "Olivia King",
    lead_name: "Avery Carter",
    status: "Follow-up",
    channel: "whatsapp",
    source: "PF",
    amount: 3800000,
  },
  {
    agent_name: "Michael Smith",
    lead_name: "Natalie Allen",
    status: "Closed",
    channel: "mail",
    source: "vortexweb",
    amount: 5900000,
  },
  {
    agent_name: "Lucas Walker",
    lead_name: "Caleb Taylor",
    status: "Junk",
    channel: "website",
    source: "bayut",
    amount: 710000,
  },
  {
    agent_name: "David Scott",
    lead_name: "Hannah Young",
    status: "New Lead",
    channel: "whatsapp",
    source: "dubizzle",
    amount: 2300000,
  },
  {
    agent_name: "Olivia King",
    lead_name: "Isaac Moore",
    status: "Follow-up",
    channel: "call",
    source: "behomes",
    amount: 4600000,
  },
  {
    agent_name: "Michael Smith",
    lead_name: "Zachary Green",
    status: "Closed",
    channel: "other",
    source: "bayut",
    amount: 6000000,
  },
  {
    agent_name: "Lucas Walker",
    lead_name: "Maya Lee",
    status: "Junk",
    channel: "whatsapp",
    source: "PF",
    amount: 540000,
  },
  {
    agent_name: "David Scott",
    lead_name: "Levi Martin",
    status: "New Lead",
    channel: "mail",
    source: "vortexweb",
    amount: 3100000,
  },
  {
    agent_name: "Olivia King",
    lead_name: "Caroline White",
    status: "Follow-up",
    channel: "website",
    source: "dubizzle",
    amount: 5500000,
  },
  {
    agent_name: "Michael Smith",
    lead_name: "Matthew Adams",
    status: "Closed",
    channel: "call",
    source: "PF",
    amount: 6700000,
  },
];
