export const mockUsers = [
  {
    id: 1,
    firstName: "Alice",
    lastName: "Johnson",
    phone: "+11234567890",
    email: "alice.johnson@example.com",
    country: "United States",
    profileVisibility: "Open",
    userId: "user-1734072263120",
    userIdExtraInfo: "x462971567294141001",
    social: {
      whatsapp: "+11234567890",
      instagram: "alice_insta",
      telegram: "alice_telegram",
      facebook: "alice.fb",
    },
    position: "Real Estate Agent",
    expertise: "Residential Properties",
    experience: 5,
    languages: "English, Spanish",
    brn: "BRN-12345",
    userSettings: {
      language: "English",
      currency: "USD",
      units: "ft²",
      behomesCountry: "United States",
    },
  },
  {
    id: 2,
    firstName: "Michael",
    lastName: "Smith",
    phone: "+441234567890",
    email: "michael.smith@example.com",
    country: "United Kingdom",
    profileVisibility: "Closed",
    userId: "user-1734072263121",
    userIdExtraInfo: "x462971567294141002",
    social: {
      whatsapp: "",
      instagram: "michael_uk",
      telegram: "michael_tg",
      facebook: "",
    },
    position: "Admin",
    expertise: "Property Management",
    experience: 10,
    languages: "English, French",
    brn: "BRN-67890",
    userSettings: {
      language: "English",
      currency: "GBP",
      units: "m²",
      behomesCountry: "United Kingdom",
    },
  },
  {
    id: 3,
    firstName: "Jessica",
    lastName: "Brown",
    phone: "+331234567890",
    email: "jessica.brown@example.com",
    country: "France",
    profileVisibility: "Open",
    userId: "user-1734072263122",
    userIdExtraInfo: "x462971567294141003",
    social: {
      whatsapp: "+331234567890",
      instagram: "jessica_fr",
      telegram: "",
      facebook: "jessica.fb",
    },
    position: "Superadmin",
    expertise: "Commercial Real Estate",
    experience: 8,
    languages: "French, English",
    brn: "BRN-45678",
    userSettings: {
      language: "French",
      currency: "EUR",
      units: "m²",
      behomesCountry: "France",
    },
  },
  {
    id: 4,
    firstName: "Robert",
    lastName: "Wilson",
    phone: "+491234567890",
    email: "robert.wilson@example.com",
    country: "Germany",
    profileVisibility: "Closed",
    userId: "user-1734072263123",
    userIdExtraInfo: "x462971567294141004",
    social: {
      whatsapp: "+491234567890",
      instagram: "",
      telegram: "robert_telegram",
      facebook: "robert.fb",
    },
    position: "Real Estate Agent",
    expertise: "Luxury Apartments",
    experience: 6,
    languages: "German, English",
    brn: "BRN-78901",
    userSettings: {
      language: "German",
      currency: "EUR",
      units: "m²",
      behomesCountry: "Germany",
    },
  },
  {
    id: 5,
    firstName: "Emma",
    lastName: "Thompson",
    phone: "+61234567890",
    email: "emma.thompson@example.com",
    country: "Australia",
    profileVisibility: "Open",
    userId: "user-1734072263124",
    userIdExtraInfo: "x462971567294141005",
    social: {
      whatsapp: "",
      instagram: "emma_aussie",
      telegram: "",
      facebook: "emma.fb",
    },
    position: "Admin",
    expertise: "Property Law",
    experience: 12,
    languages: "English",
    brn: "BRN-54321",
    userSettings: {
      language: "English",
      currency: "AUD",
      units: "m²",
      behomesCountry: "Australia",
    },
  },
  {
    id: 6,
    firstName: "Daniel",
    lastName: "Martinez",
    phone: "+521234567890",
    email: "daniel.martinez@example.com",
    country: "Mexico",
    profileVisibility: "Closed",
    userId: "user-1734072263125",
    userIdExtraInfo: "x462971567294141006",
    social: {
      whatsapp: "+521234567890",
      instagram: "daniel_mex",
      telegram: "",
      facebook: "",
    },
    position: "Superadmin",
    expertise: "Investment Properties",
    experience: 15,
    languages: "Spanish, English",
    brn: "BRN-23456",
    userSettings: {
      language: "Spanish",
      currency: "MXN",
      units: "m²",
      behomesCountry: "Mexico",
    },
  },
  {
    id: 7,
    firstName: "Sophia",
    lastName: "Anderson",
    phone: "+141234567890",
    email: "sophia.anderson@example.com",
    country: "Canada",
    profileVisibility: "Open",
    userId: "user-1734072263126",
    userIdExtraInfo: "x462971567294141007",
    social: {
      whatsapp: "",
      instagram: "sophia_canada",
      telegram: "",
      facebook: "sophia.fb",
    },
    position: "Real Estate Agent",
    expertise: "Vacation Homes",
    experience: 7,
    languages: "English, French",
    brn: "BRN-56789",
    userSettings: {
      language: "English",
      currency: "CAD",
      units: "ft²",
      behomesCountry: "Canada",
    },
  },
  {
    id: 8,
    firstName: "David",
    lastName: "Scott",
    phone: "+821234567890",
    email: "david.scott@example.com",
    country: "South Korea",
    profileVisibility: "Closed",
    userId: "user-1734072263127",
    userIdExtraInfo: "x462971567294141008",
    social: {
      whatsapp: "",
      instagram: "",
      telegram: "david_korea",
      facebook: "david.fb",
    },
    position: "Admin",
    expertise: "Commercial Leasing",
    experience: 9,
    languages: "Korean, English",
    brn: "BRN-67890",
    userSettings: {
      language: "Korean",
      currency: "KRW",
      units: "m²",
      behomesCountry: "South Korea",
    },
  },
  {
    id: 9,
    firstName: "Olivia",
    lastName: "King",
    phone: "+911234567890",
    email: "olivia.king@example.com",
    country: "India",
    profileVisibility: "Open",
    userId: "user-1734072263128",
    userIdExtraInfo: "x462971567294141009",
    social: {
      whatsapp: "+911234567890",
      instagram: "olivia_india",
      telegram: "",
      facebook: "",
    },
    position: "Superadmin",
    expertise: "Affordable Housing",
    experience: 11,
    languages: "Hindi, English",
    brn: "BRN-34567",
    userSettings: {
      language: "English",
      currency: "INR",
      units: "ft²",
      behomesCountry: "India",
    },
  },
  {
    id: 10,
    firstName: "Lucas",
    lastName: "Walker",
    phone: "+551234567890",
    email: "lucas.walker@example.com",
    country: "Brazil",
    profileVisibility: "Closed",
    userId: "user-1734072263129",
    userIdExtraInfo: "x462971567294141010",
    social: {
      whatsapp: "",
      instagram: "lucas_brazil",
      telegram: "",
      facebook: "lucas.fb",
    },
    position: "Real Estate Agent",
    expertise: "Eco-friendly Homes",
    experience: 6,
    languages: "Portuguese, English",
    brn: "BRN-12367",
    userSettings: {
      language: "Portuguese",
      currency: "BRL",
      units: "m²",
      behomesCountry: "Brazil",
    },
  },
];

// mockdata for property cards

export const cards = [
  {
    image:
      "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Skyline Heights",
    developer: "Urban Edge Properties",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "123 Liberty St, New York, NY",
    walkingTime: "5",
    isPopular: true,
    isCompleted: true,
    amenities: [
      "Rooftop garden",
      "24/7 security",
      "Fitness center",
      "Co-working space",
      "Indoor pool",
      "Pet-friendly",
      "Concierge service",
      "Private theater",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-26548",
  },
  {
    image:
      "https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Oceanview Residences",
    developer: "Seaside Developments",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "456 Ocean Ave, Santa Monica, CA",
    walkingTime: "2",
    isPopular: true,
    isCompleted: false,
    amenities: [
      "Beach access",
      "Infinity pool",
      "Spa and wellness center",
      "Gourmet dining",
      "Yoga studio",
      "Valet parking",
      "Private balconies",
      "Smart home technology",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-37635",
  },
  {
    image:
      "https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Mountain Retreat",
    developer: "Highland Estates",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "789 Alpine Rd, Aspen, CO",
    walkingTime: "10",
    isPopular: false,
    isCompleted: true,
    amenities: [
      "Ski-in/ski-out access",
      "Heated floors",
      "Fireplace lounges",
      "Private hot tubs",
      "Gourmet kitchens",
      "Wine cellars",
      "Home theaters",
      "Game rooms",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-44356",
  },
  {
    image:
      "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Urban Oasis",
    developer: "Cityscape Builders",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "321 Wacker Dr, Chicago, IL",
    walkingTime: "3",
    isPopular: true,
    isCompleted: false,
    amenities: [
      "Sky lounge",
      "Fitness center",
      "Indoor pool",
      "Business center",
      "Pet spa",
      "Outdoor terrace",
      "Bike storage",
      "On-site retail",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-29196",
  },
  {
    image:
      "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Lakeside Villas",
    developer: "Tranquil Living",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "654 Serenity Ln, South Lake Tahoe, CA",
    walkingTime: "7",
    isPopular: false,
    isCompleted: true,
    amenities: [
      "Private docks",
      "Lakeside views",
      "Gourmet kitchens",
      "Fire pits",
      "Outdoor kitchens",
      "Jacuzzis",
      "Home automation",
      "Security systems",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-74962",
  },
  {
    image:
      "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Countryside Manor",
    developer: "Heritage Homes",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "987 Country Rd, Nashville, TN",
    walkingTime: "15",
    isPopular: false,
    isCompleted: false,
    amenities: [
      "Horse stables",
      "Private gardens",
      "Gated entry",
      "Chef's kitchen",
      "Wine cellar",
      "Library",
      "Home office",
      "Outdoor pool",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-17999",
  },
  {
    image:
      "https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Seaside Escape",
    developer: "Coastal Builders",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "123 Ocean Drive, Miami Beach, FL",
    walkingTime: "2",
    isPopular: true,
    isCompleted: true,
    amenities: [
      "Horse stables",
      "Private gardens",
      "Gated entry",
      "Chef's kitchen",
      "Wine cellar",
      "Library",
      "Home office",
      "Outdoor pool",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-40212",
  },
  {
    image:
      "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Sky Tower",
    developer: "Metropolitan Properties",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "789 Market St, San Francisco, CA",
    walkingTime: "5",
    isPopular: true,
    isCompleted: false,
    amenities: [
      "Rooftop infinity pool",
      "24/7 concierge",
      "Luxury spa",
      "Movie theater",
      "Private lounges",
      "Gourmet dining options",
      "Pet-friendly facilities",
      "Smart home automation",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-43607",
  },
  {
    image:
      "https://images.pexels.com/photos/136407/pexels-photo-136407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Palm Grove Residences",
    developer: "Sunset Developers",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "567 Sunset Blvd, Los Angeles, CA",
    walkingTime: "3",
    isPopular: true,
    isCompleted: true,
    amenities: [
      "Private rooftop gardens",
      "Resort-style pool",
      "Full-service gym",
      "High-speed internet",
      "Pet park",
      "Personalized butler service",
      "Exclusive residents' club",
      "State-of-the-art security",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-84717",
  },
  {
    image:
      "https://images.pexels.com/photos/208736/pexels-photo-208736.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Evergreen Towers",
    developer: "Green Living Estates",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "222 Pine St, Seattle, WA",
    walkingTime: "4",
    isPopular: false,
    isCompleted: true,
    amenities: [
      "Eco-friendly design",
      "Solar energy solutions",
      "Community garden",
      "Yoga & meditation rooms",
      "Private balconies",
      "On-site co-working space",
      "EV charging stations",
      "Luxury clubhouse",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-29684",
  },
  {
    image:
      "https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Central Park Lofts",
    developer: "Modern Living Developers",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "101 5th Ave, Manhattan, NY",
    walkingTime: "2",
    isPopular: true,
    isCompleted: false,
    amenities: [
      "Private rooftop terraces",
      "Gym with personal trainers",
      "Luxury spa treatments",
      "High-speed elevators",
      "On-site wine bar",
      "Concierge for residents",
      "Soundproof music rooms",
      "Exclusive shopping access",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-97237",
  },
  {
    image:
      "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Lakeside Villas",
    developer: "Tranquil Living",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "654 Serenity Ln, South Lake Tahoe, CA",
    walkingTime: "7",
    isPopular: false,
    isCompleted: true,
    amenities: [
      "Private docks",
      "Lakeside views",
      "Gourmet kitchens",
      "Fire pits",
      "Outdoor kitchens",
      "Jacuzzis",
      "Home automation",
      "Security systems",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-12642",
  },
  {
    image:
      "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Countryside Manor",
    developer: "Heritage Homes",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "987 Country Rd, Nashville, TN",
    walkingTime: "15",
    isPopular: false,
    isCompleted: false,
    amenities: [
      "Horse stables",
      "Private gardens",
      "Gated entry",
      "Chef's kitchen",
      "Wine cellar",
      "Library",
      "Home office",
      "Outdoor pool",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-2429",
  },
  {
    image:
      "https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Seaside Escape",
    developer: "Coastal Builders",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "123 Ocean Drive, Miami Beach, FL",
    walkingTime: "2",
    isPopular: true,
    isCompleted: true,
    amenities: [
      "Horse stables",
      "Private gardens",
      "Gated entry",
      "Chef's kitchen",
      "Wine cellar",
      "Library",
      "Home office",
      "Outdoor pool",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-54166",
  },
  {
    image:
      "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Sky Tower",
    developer: "Metropolitan Properties",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "789 Market St, San Francisco, CA",
    walkingTime: "5",
    isPopular: true,
    isCompleted: false,
    amenities: [
      "Rooftop infinity pool",
      "24/7 concierge",
      "Luxury spa",
      "Movie theater",
      "Private lounges",
      "Gourmet dining options",
      "Pet-friendly facilities",
      "Smart home automation",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-77305",
  },
  {
    image:
      "https://images.pexels.com/photos/136407/pexels-photo-136407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Palm Grove Residences",
    developer: "Sunset Developers",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "567 Sunset Blvd, Los Angeles, CA",
    walkingTime: "3",
    isPopular: true,
    isCompleted: true,
    amenities: [
      "Private rooftop gardens",
      "Resort-style pool",
      "Full-service gym",
      "High-speed internet",
      "Pet park",
      "Personalized butler service",
      "Exclusive residents' club",
      "State-of-the-art security",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-34700",
  },
  {
    image:
      "https://images.pexels.com/photos/208736/pexels-photo-208736.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Evergreen Towers",
    developer: "Green Living Estates",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "222 Pine St, Seattle, WA",
    walkingTime: "4",
    isPopular: false,
    isCompleted: true,
    amenities: [
      "Eco-friendly design",
      "Solar energy solutions",
      "Community garden",
      "Yoga & meditation rooms",
      "Private balconies",
      "On-site co-working space",
      "EV charging stations",
      "Luxury clubhouse",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-74248",
  },
  {
    image:
      "https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Central Park Lofts",
    developer: "Modern Living Developers",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "101 5th Ave, Manhattan, NY",
    walkingTime: "2",
    isPopular: true,
    isCompleted: false,
    amenities: [
      "Private rooftop terraces",
      "Gym with personal trainers",
      "Luxury spa treatments",
      "High-speed elevators",
      "On-site wine bar",
      "Concierge for residents",
      "Soundproof music rooms",
      "Exclusive shopping access",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-64851",
  },
  {
    image:
      "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Lakeside Villas",
    developer: "Tranquil Living",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "654 Serenity Ln, South Lake Tahoe, CA",
    walkingTime: "7",
    isPopular: false,
    isCompleted: true,
    amenities: [
      "Private docks",
      "Lakeside views",
      "Gourmet kitchens",
      "Fire pits",
      "Outdoor kitchens",
      "Jacuzzis",
      "Home automation",
      "Security systems",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-48255",
  },
  {
    image:
      "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Countryside Manor",
    developer: "Heritage Homes",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "987 Country Rd, Nashville, TN",
    walkingTime: "15",
    isPopular: false,
    isCompleted: false,
    amenities: [
      "Horse stables",
      "Private gardens",
      "Gated entry",
      "Chef's kitchen",
      "Wine cellar",
      "Library",
      "Home office",
      "Outdoor pool",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-20120",
  },
  {
    image:
      "https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Seaside Escape",
    developer: "Coastal Builders",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "123 Ocean Drive, Miami Beach, FL",
    walkingTime: "2",
    isPopular: true,
    isCompleted: true,
    amenities: [
      "Horse stables",
      "Private gardens",
      "Gated entry",
      "Chef's kitchen",
      "Wine cellar",
      "Library",
      "Home office",
      "Outdoor pool",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-74558",
  },
  {
    image:
      "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Sky Tower",
    developer: "Metropolitan Properties",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "789 Market St, San Francisco, CA",
    walkingTime: "5",
    isPopular: true,
    isCompleted: false,
    amenities: [
      "Rooftop infinity pool",
      "24/7 concierge",
      "Luxury spa",
      "Movie theater",
      "Private lounges",
      "Gourmet dining options",
      "Pet-friendly facilities",
      "Smart home automation",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-6484",
  },
  {
    image:
      "https://images.pexels.com/photos/136407/pexels-photo-136407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Palm Grove Residences",
    developer: "Sunset Developers",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "567 Sunset Blvd, Los Angeles, CA",
    walkingTime: "3",
    isPopular: true,
    isCompleted: true,
    amenities: [
      "Private rooftop gardens",
      "Resort-style pool",
      "Full-service gym",
      "High-speed internet",
      "Pet park",
      "Personalized butler service",
      "Exclusive residents' club",
      "State-of-the-art security",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-77213",
  },
  {
    image:
      "https://images.pexels.com/photos/208736/pexels-photo-208736.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Evergreen Towers",
    developer: "Green Living Estates",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "222 Pine St, Seattle, WA",
    walkingTime: "4",
    isPopular: false,
    isCompleted: true,
    amenities: [
      "Eco-friendly design",
      "Solar energy solutions",
      "Community garden",
      "Yoga & meditation rooms",
      "Private balconies",
      "On-site co-working space",
      "EV charging stations",
      "Luxury clubhouse",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-69539",
  },
  {
    image:
      "https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Central Park Lofts",
    developer: "Modern Living Developers",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "101 5th Ave, Manhattan, NY",
    walkingTime: "2",
    isPopular: true,
    isCompleted: false,
    amenities: [
      "Private rooftop terraces",
      "Gym with personal trainers",
      "Luxury spa treatments",
      "High-speed elevators",
      "On-site wine bar",
      "Concierge for residents",
      "Soundproof music rooms",
      "Exclusive shopping access",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-40591",
  },
  {
    image:
      "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Lakeside Villas",
    developer: "Tranquil Living",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "654 Serenity Ln, South Lake Tahoe, CA",
    walkingTime: "7",
    isPopular: false,
    isCompleted: true,
    amenities: [
      "Private docks",
      "Lakeside views",
      "Gourmet kitchens",
      "Fire pits",
      "Outdoor kitchens",
      "Jacuzzis",
      "Home automation",
      "Security systems",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-4279",
  },
  {
    image:
      "https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Countryside Manor",
    developer: "Heritage Homes",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "987 Country Rd, Nashville, TN",
    walkingTime: "15",
    isPopular: false,
    isCompleted: false,
    amenities: [
      "Horse stables",
      "Private gardens",
      "Gated entry",
      "Chef's kitchen",
      "Wine cellar",
      "Library",
      "Home office",
      "Outdoor pool",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-42308",
  },
  {
    image:
      "https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Seaside Escape",
    developer: "Coastal Builders",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "123 Ocean Drive, Miami Beach, FL",
    walkingTime: "2",
    isPopular: true,
    isCompleted: true,
    amenities: [
      "Horse stables",
      "Private gardens",
      "Gated entry",
      "Chef's kitchen",
      "Wine cellar",
      "Library",
      "Home office",
      "Outdoor pool",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-50218",
  },
  {
    image:
      "https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Sky Tower",
    developer: "Metropolitan Properties",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "789 Market St, San Francisco, CA",
    walkingTime: "5",
    isPopular: true,
    isCompleted: false,
    amenities: [
      "Rooftop infinity pool",
      "24/7 concierge",
      "Luxury spa",
      "Movie theater",
      "Private lounges",
      "Gourmet dining options",
      "Pet-friendly facilities",
      "Smart home automation",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-49529",
  },
  {
    image:
      "https://images.pexels.com/photos/136407/pexels-photo-136407.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Palm Grove Residences",
    developer: "Sunset Developers",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "567 Sunset Blvd, Los Angeles, CA",
    walkingTime: "3",
    isPopular: true,
    isCompleted: true,
    amenities: [
      "Private rooftop gardens",
      "Resort-style pool",
      "Full-service gym",
      "High-speed internet",
      "Pet park",
      "Personalized butler service",
      "Exclusive residents' club",
      "State-of-the-art security",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-74057",
  },
  {
    image:
      "https://images.pexels.com/photos/208736/pexels-photo-208736.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Evergreen Towers",
    developer: "Green Living Estates",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "222 Pine St, Seattle, WA",
    walkingTime: "4",
    isPopular: false,
    isCompleted: true,
    amenities: [
      "Eco-friendly design",
      "Solar energy solutions",
      "Community garden",
      "Yoga & meditation rooms",
      "Private balconies",
      "On-site co-working space",
      "EV charging stations",
      "Luxury clubhouse",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-4701",
  },
  {
    image:
      "https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Central Park Lofts",
    developer: "Modern Living Developers",
    price: "From 3 750 000",
    description: "2 bed, 1 bath, 1,000 sq ft",
    rating: 4.5,
    location: "Beachfront",
    address: "101 5th Ave, Manhattan, NY",
    walkingTime: "2",
    isPopular: true,
    isCompleted: false,
    amenities: [
      "Private rooftop terraces",
      "Gym with personal trainers",
      "Luxury spa treatments",
      "High-speed elevators",
      "On-site wine bar",
      "Concierge for residents",
      "Soundproof music rooms",
      "Exclusive shopping access",
    ],
    layouts: [[Object], [Object]],
    id: "1740391654985-80310",
  },
];

export const secondaryListings = [
  {
    management: {
      reference: "REF001",
      listingAgent: "John Doe",
      listingOwner: "Jane Smith",
      landlordName: "Ali Al-Mansoori",
      landlordEmail: "ali@landlord.com",
      landlordPhone: "+971501234567",
      availability: "Available",
      availableFrom: "2025-02-25",
    },
    specifications: {
      property_type: "Apartment",
      category: "Residential Rent",
      size: 1200,
      noOfBedrooms: 2,
      noOfBathrooms: 2,
      noOfParkingSpaces: 1,
      furnished: "Furnished",
      total_plot_size: 1200,
    },
    pricing: {
      price: 75000,
      rentalPeriod: "Yearly",
    },
    titleAndDescription: {
      title: "Luxury Apartment in Downtown",
      description:
        "A stunning luxury apartment located in the heart of the city.",
    },
    location: {
      propertyFinder: {
        location: "Downtown Dubai",
      },
      bayut: {
        location: "Downtown Dubai",
      },
      city: "Dubai",
      community: "Downtown",
      subCommunity: "Burj Khalifa",
      building: "Burj Views",
    },
    propertyImages: ["image1.jpg", "image2.jpg"],
    floorPlanImages: ["floorplan1.jpg"],
  },
  {
    management: {
      reference: "REF002",
      listingAgent: "Sarah Lee",
      listingOwner: "Mohammed Khan",
      landlordName: "Fatima Al-Farsi",
      landlordEmail: "fatima@landlord.com",
      landlordPhone: "+971501234568",
      availability: "Under Offer",
      availableFrom: "2025-02-20",
    },
    specifications: {
      property_type: "Villa",
      category: "Residential Sale",
      size: 3000,
      noOfBedrooms: 4,
      noOfBathrooms: 3,
      noOfParkingSpaces: 2,
      furnished: "Semi Furnished",
      total_plot_size: 3500,
    },
    pricing: {
      price: 2500000,
      rentalPeriod: null,
    },
    titleAndDescription: {
      title: "Spacious Villa in Arabian Ranches",
      description: "A beautiful villa with a private garden and pool.",
    },
    location: {
      propertyFinder: {
        location: "Arabian Ranches",
      },
      bayut: {
        location: "Arabian Ranches",
      },
      city: "Dubai",
      community: "Arabian Ranches",
      subCommunity: "Arabian Ranches 1",
      building: null,
    },
    propertyImages: ["image3.jpg", "image4.jpg"],
    floorPlanImages: ["floorplan2.jpg"],
  },
  {
    management: {
      reference: "REF003",
      listingAgent: "Michael Brown",
      listingOwner: "Laila Ahmed",
      landlordName: "Omar Al-Hamadi",
      landlordEmail: "omar@landlord.com",
      landlordPhone: "+971501234569",
      availability: "Reserved",
      availableFrom: "2025-03-01",
    },
    specifications: {
      property_type: "Penthouse",
      category: "Residential Sale",
      size: 4000,
      noOfBedrooms: 5,
      noOfBathrooms: 5,
      noOfParkingSpaces: 3,
      furnished: "Furnished",
      total_plot_size: 4500,
    },
    pricing: {
      price: 5000000,
      rentalPeriod: null,
    },
    titleAndDescription: {
      title: "Exclusive Penthouse with Sea View",
      description: "Luxury living with breathtaking views of the sea.",
    },
    location: {
      propertyFinder: {
        location: "Dubai Marina",
      },
      bayut: {
        location: "Dubai Marina",
      },
      city: "Dubai",
      community: "Dubai Marina",
      subCommunity: "Marina Heights",
      building: "Marina Heights Tower",
    },
    propertyImages: ["image5.jpg", "image6.jpg"],
    floorPlanImages: ["floorplan3.jpg"],
  },
  {
    management: {
      reference: "REF004",
      listingAgent: "Emily White",
      listingOwner: "Zayed Ali",
      landlordName: "Nora Al-Suwaidi",
      landlordEmail: "nora@landlord.com",
      landlordPhone: "+971501234570",
      availability: "Sold",
      availableFrom: null,
    },
    specifications: {
      property_type: "Townhouse",
      category: "Residential Sale",
      size: 2500,
      noOfBedrooms: 3,
      noOfBathrooms: 2,
      noOfParkingSpaces: 2,
      furnished: "Unfurnished",
      total_plot_size: 3000,
    },
    pricing: {
      price: 1800000,
      rentalPeriod: null,
    },
    titleAndDescription: {
      title: "Modern Townhouse in Jumeirah",
      description: "A modern townhouse with easy access to the beach.",
    },
    location: {
      propertyFinder: {
        location: "Jumeirah",
      },
      bayut: {
        location: "Jumeirah",
      },
      city: "Dubai",
      community: "Jumeirah",
      subCommunity: "Jumeirah 1",
      building: null,
    },
    propertyImages: ["image7.jpg", "image8.jpg"],
    floorPlanImages: ["floorplan4.jpg"],
  },
  {
    management: {
      reference: "REF005",
      listingAgent: "David Green",
      listingOwner: "Sara Nasser",
      landlordName: "Khalid Al-Qasimi",
      landlordEmail: "khalid@landlord.com",
      landlordPhone: "+971501234571",
      availability: "Available",
      availableFrom: "2025-02-15",
    },
    specifications: {
      property_type: "Apartment",
      category: "Commercial Rent",
      size: 800,
      noOfBedrooms: 1,
      noOfBathrooms: 1,
      noOfParkingSpaces: 1,
      furnished: "Furnished",
      total_plot_size: 800,
    },
    pricing: {
      price: 60000,
      rentalPeriod: "Yearly",
    },
    titleAndDescription: {
      title: "Cozy Apartment for Rent",
      description: "Perfect for singles or couples looking for a cozy space.",
    },
    location: {
      propertyFinder: {
        location: "Business Bay",
      },
      bayut: {
        location: "Business Bay",
      },
      city: "Dubai",
      community: "Business Bay",
      subCommunity: null,
      building: "Business Tower",
    },
    propertyImages: ["image9.jpg", "image10.jpg"],
    floorPlanImages: ["floorplan5.jpg"],
  },
  // Add more objects as needed
];

//  mock data for layouts
export const layouts = [
  {
    id: "layout-1",
    type: "2 Bedrooms",
    area: 810.0,
    areaUnit: "ft²",
    building: "Tower A",
    floor: "15",
    unitNumber: "1502",
    price: 4521807,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout1.png",
    status: "Completed",
    rooms: {
      bedrooms: 2,
      bathrooms: 2,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Balcony", "Maid's Room"],
  },
  {
    id: "layout-2",
    type: "3 Bedrooms",
    area: 1200.0,
    areaUnit: "ft²",
    building: "Tower B",
    floor: "20",
    unitNumber: "2001",
    price: 6750000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout2.png",
    status: "Available",
    rooms: {
      bedrooms: 3,
      bathrooms: 3,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Balcony", "Study Room", "Maid's Room"],
  },
  {
    id: "layout-3",
    type: "1 Bedroom",
    area: 650.0,
    areaUnit: "ft²",
    building: "Tower A",
    floor: "10",
    unitNumber: "1003",
    price: 2850000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout3.png",
    status: "Completed",
    rooms: {
      bedrooms: 1,
      bathrooms: 1.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Balcony"],
  },
  {
    id: "layout-4",
    type: "Studio",
    area: 450.0,
    areaUnit: "ft²",
    building: "Tower C",
    floor: "5",
    unitNumber: "504",
    price: 1950000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout4.png",
    status: "Sold",
    rooms: {
      bedrooms: 0,
      bathrooms: 1,
    },
    isAvailable: false,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "City View"],
  },
  {
    id: "layout-5",
    type: "4 Bedrooms",
    area: 2100.0,
    areaUnit: "ft²",
    building: "Tower B",
    floor: "25",
    unitNumber: "2501",
    price: 8900000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout1.png",
    status: "Available",
    rooms: {
      bedrooms: 4,
      bathrooms: 4.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: [
      "Open Kitchen",
      "Balcony",
      "Maid's Room",
      "Study Room",
      "Private Pool",
    ],
  },
  {
    id: "layout-6",
    type: "2 Bedrooms",
    area: 950.0,
    areaUnit: "ft²",
    building: "Tower D",
    floor: "12",
    unitNumber: "1205",
    price: 4980000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout2.png",
    status: "Reserved",
    rooms: {
      bedrooms: 2,
      bathrooms: 2.5,
    },
    isAvailable: false,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Balcony", "Study Nook"],
  },
  {
    id: "layout-7",
    type: "3 Bedrooms",
    area: 1450.0,
    areaUnit: "ft²",
    building: "Tower C",
    floor: "18",
    unitNumber: "1802",
    price: 7200000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout3.png",
    status: "Completed",
    rooms: {
      bedrooms: 3,
      bathrooms: 3.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Dual Balcony", "Maid's Room", "Storage Room"],
  },
  {
    id: "layout-8",
    type: "Penthouse",
    area: 3200.0,
    areaUnit: "ft²",
    building: "Tower A",
    floor: "30",
    unitNumber: "PH01",
    price: 15800000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout4.png",
    status: "Available",
    rooms: {
      bedrooms: 5,
      bathrooms: 5.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: [
      "Open Kitchen",
      "Wraparound Balcony",
      "Maid's Room",
      "Study Room",
      "Private Pool",
      "Private Elevator",
    ],
  },
  {
    id: "layout-9",
    type: "1 Bedroom",
    area: 750.0,
    areaUnit: "ft²",
    building: "Tower D",
    floor: "8",
    unitNumber: "805",
    price: 3250000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout1.png",
    status: "Completed",
    rooms: {
      bedrooms: 1,
      bathrooms: 2,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Large Balcony", "Study Nook"],
  },
  {
    id: "layout-10",
    type: "2 Bedrooms + Study",
    area: 1100.0,
    areaUnit: "ft²",
    building: "Tower B",
    floor: "22",
    unitNumber: "2204",
    price: 5650000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout2.png",
    status: "Available",
    rooms: {
      bedrooms: 2,
      bathrooms: 2.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Dual Balcony", "Study Room", "Storage Room"],
  },
  {
    id: "layout-7",
    type: "3 Bedrooms",
    area: 1450.0,
    areaUnit: "ft²",
    building: "Tower C",
    floor: "18",
    unitNumber: "1802",
    price: 7200000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout3.png",
    status: "Completed",
    rooms: {
      bedrooms: 3,
      bathrooms: 3.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Dual Balcony", "Maid's Room", "Storage Room"],
  },
  {
    id: "layout-7",
    type: "3 Bedrooms",
    area: 1450.0,
    areaUnit: "ft²",
    building: "Tower C",
    floor: "18",
    unitNumber: "1802",
    price: 7200000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout3.png",
    status: "Completed",
    rooms: {
      bedrooms: 3,
      bathrooms: 3.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Dual Balcony", "Maid's Room", "Storage Room"],
  },
  {
    id: "layout-7",
    type: "3 Bedrooms",
    area: 1450.0,
    areaUnit: "ft²",
    building: "Tower C",
    floor: "18",
    unitNumber: "1802",
    price: 7200000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout3.png",
    status: "Completed",
    rooms: {
      bedrooms: 3,
      bathrooms: 3.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Dual Balcony", "Maid's Room", "Storage Room"],
  },
  {
    id: "layout-7",
    type: "3 Bedrooms",
    area: 1450.0,
    areaUnit: "ft²",
    building: "Tower C",
    floor: "18",
    unitNumber: "1802",
    price: 7200000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout3.png",
    status: "Completed",
    rooms: {
      bedrooms: 3,
      bathrooms: 3.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Dual Balcony", "Maid's Room", "Storage Room"],
  },
  {
    id: "layout-7",
    type: "3 Bedrooms",
    area: 1450.0,
    areaUnit: "ft²",
    building: "Tower C",
    floor: "18",
    unitNumber: "1802",
    price: 7200000,
    currency: "د.إ",
    projectName: "Lucent33",
    developer: "ZD Jasper Realty",
    floorPlanImage: "layout3.png",
    status: "Completed",
    rooms: {
      bedrooms: 3,
      bathrooms: 3.5,
    },
    isAvailable: true,
    lastUpdated: "2024-02-14",
    features: ["Open Kitchen", "Dual Balcony", "Maid's Room", "Storage Room"],
  },
];

export const courses = [
  {
    id: 1,
    name: "Advanced Web Development",
    description: "Learn modern web development techniques and best practices",
    lectureCount: 24,
    source: "Bayut",
    tags: ["Web Development", "Frontend"],
  },
  {
    id: 2,
    name: "Data Science Fundamentals",
    description:
      "Explore data analysis, visualization, and machine learning concepts",
    lectureCount: 30,
    source: "Dubizzle",
    tags: [
      "Data Science",
      "Machine Learning",
      "Data Analysis",
      "Data Handling",
    ],
  },
  {
    id: 3,
    name: "Mobile App Development",
    description:
      "Build native and cross-platform mobile applications from scratch",
    lectureCount: 20,
    source: "BWC",
    tags: [
      "Mobile Development",
      "Cross-Platform",
      "App Development",
      "Frontend",
    ],
  },
  {
    id: 4,
    name: "Cybersecurity Essentials",
    description:
      "Understand key cybersecurity principles and practices to protect systems",
    lectureCount: 18,
    source: "Emaar",
    tags: [
      "Cybersecurity",
      "Security Principles",
      "System Protection",
      "Data Handling",
    ],
  },
  {
    id: 5,
    name: "Cloud Computing Mastery",
    description:
      "Dive into cloud infrastructure, deployment, and services management",
    lectureCount: 25,
    source: "Raheja",
    tags: ["Cloud Computing", "Cloud Infrastructure", "Deployment", "Services"],
  },
  {
    id: 6,
    name: "CRM Management",
    description:
      "Dive into CRM Management, customization, and services management",
    lectureCount: 25,
    source: "Raheja",
    tags: ["CRM", "Pipelines", "Services"],
  },
];

export const lessonsData = [
  {
    id: 1,
    sequence: 1,
    title: "Introduction to React Fundamentals",
    duration: "45 mins",
    type: "video",
    description:
      "Learn the core concepts of React and its component-based architecture",
    isLocked: false,
    completed: true,
  },
  {
    id: 2,
    sequence: 2,
    title: "State Management in React",
    duration: "55 mins",
    type: "video",
    description: "Deep dive into useState, useEffect and component lifecycle",
    isLocked: false,
    completed: true,
  },
  {
    id: 3,
    sequence: 3,
    title: "Props and Component Communication",
    duration: "40 mins",
    type: "video",
    description: "Understanding data flow between React components",
    isLocked: false,
    completed: false,
  },
  {
    id: 4,
    sequence: 4,
    title: "React Hooks in Detail",
    duration: "60 mins",
    type: "video",
    description: "Comprehensive guide to built-in React hooks",
    isLocked: false,
    completed: false,
  },
  {
    id: 5,
    sequence: 5,
    title: "Advanced State Management",
    duration: "50 mins",
    type: "video",
    description: "Context API, Redux, and other state management solutions",
    isLocked: true,
    completed: false,
  },
  {
    id: 6,
    sequence: 6,
    title: "React Router and Navigation",
    duration: "35 mins",
    type: "video",
    description: "Building multi-page applications with React Router",
    isLocked: true,
    completed: false,
  },
  {
    id: 7,
    sequence: 7,
    title: "Forms and User Input",
    duration: "45 mins",
    type: "video",
    description: "Handling forms, validation, and user input in React",
    isLocked: true,
    completed: false,
  },
  {
    id: 8,
    sequence: 8,
    title: "API Integration",
    duration: "55 mins",
    type: "video",
    description: "Working with REST APIs and handling async operations",
    isLocked: true,
    completed: false,
  },
  {
    id: 9,
    sequence: 9,
    title: "Performance Optimization",
    duration: "50 mins",
    type: "video",
    description: "Techniques to optimize React application performance",
    isLocked: true,
    completed: false,
  },
  {
    id: 10,
    sequence: 10,
    title: "Deployment and Best Practices",
    duration: "40 mins",
    type: "video",
    description: "Deploying React apps and following industry best practices",
    isLocked: true,
    completed: false,
  },
];

// Lead Mock Data

export const mockLeads = [
  {
    id: 1,
    agent_name: "Alice Johnson",
    lead_name: "John Doe",
    status: "New Lead",
    channel: "whatsapp",
    source: "PF",
    amount: 1250000,
  },
  {
    id: 2,
    agent_name: "Michael Smith",
    lead_name: "Sarah Lee",
    status: "Follow-up",
    channel: "mail",
    source: "dubizzle",
    amount: 3200000,
  },
  {
    id: 3,
    agent_name: "Jessica Brown",
    lead_name: "David Kim",
    status: "Closed",
    channel: "call",
    source: "behomes",
    amount: 4500000,
  },
  {
    id: 4,
    agent_name: "Robert Wilson",
    lead_name: "Emily Davis",
    status: "Junk",
    channel: "website",
    source: "bayut",
    amount: 700000,
  },
  {
    id: 5,
    agent_name: "Emma Thompson",
    lead_name: "James White",
    status: "New Lead",
    channel: "other",
    source: "vortexweb",
    amount: 2800000,
  },
  {
    id: 6,
    agent_name: "Daniel Martinez",
    lead_name: "Olivia Harris",
    status: "Follow-up",
    channel: "whatsapp",
    source: "dubizzle",
    amount: 5400000,
  },
  {
    id: 7,
    agent_name: "Sophia Anderson",
    lead_name: "William Carter",
    status: "Closed",
    channel: "mail",
    source: "other",
    amount: 6300000,
  },
  {
    id: 8,
    agent_name: "David Scott",
    lead_name: "Mia Robinson",
    status: "Junk",
    channel: "call",
    source: "behomes",
    amount: 850000,
  },
  {
    id: 9,
    agent_name: "Olivia King",
    lead_name: "Ethan Adams",
    status: "New Lead",
    channel: "website",
    source: "PF",
    amount: 2150000,
  },
  {
    id: 10,
    agent_name: "Lucas Walker",
    lead_name: "Ava Wright",
    status: "Follow-up",
    channel: "other",
    source: "bayut",
    amount: 4900000,
  },
  {
    id: 11,
    agent_name: "David Scott",
    lead_name: "Liam Turner",
    status: "New Lead",
    channel: "whatsapp",
    source: "PF",
    amount: 1500000,
  },
  {
    id: 12,
    agent_name: "Olivia King",
    lead_name: "Grace Mitchell",
    status: "Follow-up",
    channel: "mail",
    source: "dubizzle",
    amount: 3100000,
  },
  {
    id: 13,
    agent_name: "Michael Smith",
    lead_name: "Benjamin Clark",
    status: "Closed",
    channel: "call",
    source: "behomes",
    amount: 4700000,
  },
  {
    id: 14,
    agent_name: "Lucas Walker",
    lead_name: "Isabella Lewis",
    status: "Junk",
    channel: "website",
    source: "bayut",
    amount: 800000,
  },
  {
    id: 15,
    agent_name: "David Scott",
    lead_name: "Charlotte Evans",
    status: "New Lead",
    channel: "other",
    source: "vortexweb",
    amount: 2900000,
  },
  {
    id: 16,
    agent_name: "Olivia King",
    lead_name: "Mason Cooper",
    status: "Follow-up",
    channel: "whatsapp",
    source: "dubizzle",
    amount: 5200000,
  },
  {
    id: 17,
    agent_name: "Michael Smith",
    lead_name: "Harper Rodriguez",
    status: "Closed",
    channel: "mail",
    source: "other",
    amount: 6400000,
  },
  {
    id: 18,
    agent_name: "Lucas Walker",
    lead_name: "Sebastian Perez",
    status: "Junk",
    channel: "call",
    source: "behomes",
    amount: 950000,
  },
  {
    id: 19,
    agent_name: "David Scott",
    lead_name: "Maya Harris",
    status: "New Lead",
    channel: "website",
    source: "PF",
    amount: 2300000,
  },
  {
    id: 20,
    agent_name: "Olivia King",
    lead_name: "Jackson Robinson",
    status: "Follow-up",
    channel: "other",
    source: "bayut",
    amount: 4600000,
  },
  {
    id: 21,
    agent_name: "Michael Smith",
    lead_name: "Amelia King",
    status: "Closed",
    channel: "whatsapp",
    source: "vortexweb",
    amount: 5000000,
  },
  {
    id: 22,
    agent_name: "Lucas Walker",
    lead_name: "Evan Scott",
    status: "Junk",
    channel: "mail",
    source: "dubizzle",
    amount: 720000,
  },
  {
    id: 23,
    agent_name: "David Scott",
    lead_name: "Lily Green",
    status: "New Lead",
    channel: "call",
    source: "behomes",
    amount: 3100000,
  },
  {
    id: 24,
    agent_name: "Olivia King",
    lead_name: "Aiden Walker",
    status: "Follow-up",
    channel: "website",
    source: "bayut",
    amount: 5100000,
  },
  {
    id: 25,
    agent_name: "Michael Smith",
    lead_name: "Zoe Turner",
    status: "Closed",
    channel: "other",
    source: "PF",
    amount: 6300000,
  },
  {
    id: 26,
    agent_name: "Lucas Walker",
    lead_name: "Landon Perez",
    status: "Junk",
    channel: "whatsapp",
    source: "dubizzle",
    amount: 880000,
  },
  {
    id: 27,
    agent_name: "David Scott",
    lead_name: "Eva Walker",
    status: "New Lead",
    channel: "mail",
    source: "vortexweb",
    amount: 2500000,
  },
  {
    id: 28,
    agent_name: "Olivia King",
    lead_name: "Mila Evans",
    status: "Follow-up",
    channel: "call",
    source: "behomes",
    amount: 4300000,
  },
  {
    id: 29,
    agent_name: "Michael Smith",
    lead_name: "Ava White",
    status: "Closed",
    channel: "website",
    source: "bayut",
    amount: 5500000,
  },
  {
    id: 30,
    agent_name: "Lucas Walker",
    lead_name: "Isla Brooks",
    status: "Junk",
    channel: "other",
    source: "dubizzle",
    amount: 700000,
  },
  {
    id: 31,
    agent_name: "David Scott",
    lead_name: "Kai Carter",
    status: "New Lead",
    channel: "whatsapp",
    source: "PF",
    amount: 3800000,
  },
  {
    id: 32,
    agent_name: "Olivia King",
    lead_name: "Lucas Miller",
    status: "Follow-up",
    channel: "call",
    source: "vortexweb",
    amount: 6200000,
  },
  {
    id: 33,
    agent_name: "Michael Smith",
    lead_name: "Nora Bailey",
    status: "Closed",
    channel: "other",
    source: "dubizzle",
    amount: 5600000,
  },
  {
    id: 34,
    agent_name: "Lucas Walker",
    lead_name: "Leo Carter",
    status: "Junk",
    channel: "website",
    source: "behomes",
    amount: 750000,
  },
  {
    id: 35,
    agent_name: "David Scott",
    lead_name: "Scarlett Brown",
    status: "New Lead",
    channel: "mail",
    source: "bayut",
    amount: 2700000,
  },
  {
    id: 36,
    agent_name: "Olivia King",
    lead_name: "Benjamin Harris",
    status: "Follow-up",
    channel: "other",
    source: "PF",
    amount: 4500000,
  },
  {
    id: 37,
    agent_name: "Michael Smith",
    lead_name: "Eleanor Garcia",
    status: "Closed",
    channel: "call",
    source: "behomes",
    amount: 6800000,
  },
  {
    id: 38,
    agent_name: "Lucas Walker",
    lead_name: "Oliver Scott",
    status: "Junk",
    channel: "whatsapp",
    source: "dubizzle",
    amount: 920000,
  },
  {
    id: 39,
    agent_name: "David Scott",
    lead_name: "Ella Davis",
    status: "New Lead",
    channel: "website",
    source: "vortexweb",
    amount: 2200000,
  },
  {
    id: 40,
    agent_name: "Olivia King",
    lead_name: "Jacob Wilson",
    status: "Follow-up",
    channel: "mail",
    source: "bayut",
    amount: 5300000,
  },
  {
    id: 41,
    agent_name: "Michael Smith",
    lead_name: "Chloe Mitchell",
    status: "Closed",
    channel: "other",
    source: "PF",
    amount: 7400000,
  },
  {
    id: 42,
    agent_name: "Lucas Walker",
    lead_name: "Grace Harris",
    status: "Junk",
    channel: "call",
    source: "dubizzle",
    amount: 650000,
  },
  {
    id: 43,
    agent_name: "David Scott",
    lead_name: "Samuel Lee",
    status: "New Lead",
    channel: "other",
    source: "behomes",
    amount: 3100000,
  },
  {
    id: 44,
    agent_name: "Olivia King",
    lead_name: "Avery Carter",
    status: "Follow-up",
    channel: "whatsapp",
    source: "PF",
    amount: 3800000,
  },
  {
    id: 45,
    agent_name: "Michael Smith",
    lead_name: "Natalie Allen",
    status: "Closed",
    channel: "mail",
    source: "vortexweb",
    amount: 5900000,
  },
  {
    id: 46,
    agent_name: "Lucas Walker",
    lead_name: "Caleb Taylor",
    status: "Junk",
    channel: "website",
    source: "bayut",
    amount: 710000,
  },
  {
    id: 47,
    agent_name: "David Scott",
    lead_name: "Hannah Young",
    status: "New Lead",
    channel: "whatsapp",
    source: "dubizzle",
    amount: 2300000,
  },
  {
    id: 48,
    agent_name: "Olivia King",
    lead_name: "Isaac Moore",
    status: "Follow-up",
    channel: "call",
    source: "behomes",
    amount: 4600000,
  },
  {
    id: 49,
    agent_name: "Michael Smith",
    lead_name: "Zachary Green",
    status: "Closed",
    channel: "other",
    source: "bayut",
    amount: 6000000,
  },
  {
    id: 50,
    agent_name: "Lucas Walker",
    lead_name: "Maya Lee",
    status: "Junk",
    channel: "whatsapp",
    source: "PF",
    amount: 540000,
  },
];

// mock deals data

export const mockDeals = [
  {
    id: 1,
    agent_name: "Alice Johnson",
    type: "invoiced",
    status: "won",
    details: {
      calls: 15,
      meetings: 5,
      emails: 12,
    },
    category: "offplan",
    location: "Dubai Marina",
    amount: 1500000,
  },
  {
    id: 2,
    agent_name: "Michael Smith",
    type: "uninvoiced",
    status: "progress",
    details: {
      calls: 10,
      meetings: 3,
      emails: 8,
    },
    category: "secondary",
    location: "Palm Jumeirah",
    amount: 2800000,
  },
  {
    id: 3,
    agent_name: "Jessica Brown",
    type: "invoiced",
    status: "onhold",
    details: {
      calls: 7,
      meetings: 2,
      emails: 6,
    },
    category: "offplan",
    location: "Downtown Dubai",
    amount: 1350000,
  },
  {
    id: 4,
    agent_name: "Robert Wilson",
    type: "uninvoiced",
    status: "progress",
    details: {
      calls: 12,
      meetings: 4,
      emails: 10,
    },
    category: "secondary",
    location: "Los Angeles",
    amount: 3200000,
  },
  {
    id: 5,
    agent_name: "Emma Thompson",
    type: "invoiced",
    status: "won",
    details: {
      calls: 20,
      meetings: 7,
      emails: 15,
    },
    category: "offplan",
    location: "Miami",
    amount: 5000000,
  },
  {
    id: 6,
    agent_name: "Daniel Martinez",
    type: "uninvoiced",
    status: "progress",
    details: {
      calls: 9,
      meetings: 3,
      emails: 7,
    },
    category: "secondary",
    location: "Abu Dhabi",
    amount: 2100000,
  },
  {
    id: 7,
    agent_name: "Sophia Anderson",
    type: "invoiced",
    status: "onhold",
    details: {
      calls: 5,
      meetings: 2,
      emails: 4,
    },
    category: "offplan",
    location: "New York",
    amount: 7500000,
  },
  {
    id: 8,
    agent_name: "David Scott",
    type: "uninvoiced",
    status: "won",
    details: {
      calls: 18,
      meetings: 6,
      emails: 13,
    },
    category: "secondary",
    location: "San Francisco",
    amount: 4300000,
  },
  {
    id: 9,
    agent_name: "Olivia King",
    type: "invoiced",
    status: "progress",
    details: {
      calls: 14,
      meetings: 5,
      emails: 10,
    },
    category: "offplan",
    location: "Business Bay",
    amount: 1950000,
  },
  {
    id: 10,
    agent_name: "Lucas Walker",
    type: "uninvoiced",
    status: "onhold",
    details: {
      calls: 6,
      meetings: 1,
      emails: 5,
    },
    category: "secondary",
    location: "Los Angeles",
    amount: 2800000,
  },
  {
    id: 11,
    agent_name: "Alice Johnson",
    type: "invoiced",
    status: "won",
    details: {
      calls: 22,
      meetings: 8,
      emails: 16,
    },
    category: "offplan",
    location: "Dubai Hills",
    amount: 6700000,
  },
  {
    id: 12,
    agent_name: "Michael Smith",
    type: "uninvoiced",
    status: "progress",
    details: {
      calls: 8,
      meetings: 2,
      emails: 6,
    },
    category: "secondary",
    location: "Abu Dhabi",
    amount: 2900000,
  },
  {
    id: 13,
    agent_name: "Jessica Brown",
    type: "invoiced",
    status: "won",
    details: {
      calls: 17,
      meetings: 6,
      emails: 14,
    },
    category: "offplan",
    location: "Manhattan",
    amount: 8800000,
  },
  {
    id: 14,
    agent_name: "Robert Wilson",
    type: "uninvoiced",
    status: "onhold",
    details: {
      calls: 12,
      meetings: 4,
      emails: 10,
    },
    category: "secondary",
    location: "Beverly Hills",
    amount: 5400000,
  },
  {
    id: 15,
    agent_name: "Emma Thompson",
    type: "invoiced",
    status: "progress",
    details: {
      calls: 9,
      meetings: 3,
      emails: 7,
    },
    category: "offplan",
    location: "Palm Jumeirah",
    amount: 4600000,
  },
  {
    id: 16,
    agent_name: "Daniel Martinez",
    type: "uninvoiced",
    status: "won",
    details: {
      calls: 11,
      meetings: 4,
      emails: 9,
    },
    category: "secondary",
    location: "Dubai Marina",
    amount: 3500000,
  },
  {
    id: 17,
    agent_name: "Sophia Anderson",
    type: "invoiced",
    status: "progress",
    details: {
      calls: 7,
      meetings: 2,
      emails: 6,
    },
    category: "offplan",
    location: "San Diego",
    amount: 4800000,
  },
  {
    id: 18,
    agent_name: "David Scott",
    type: "uninvoiced",
    status: "onhold",
    details: {
      calls: 14,
      meetings: 5,
      emails: 11,
    },
    category: "secondary",
    location: "Los Angeles",
    amount: 6000000,
  },
  {
    id: 19,
    agent_name: "Olivia King",
    type: "invoiced",
    status: "won",
    details: {
      calls: 16,
      meetings: 6,
      emails: 12,
    },
    category: "offplan",
    location: "Downtown Dubai",
    amount: 2200000,
  },
  {
    id: 20,
    agent_name: "Lucas Walker",
    type: "uninvoiced",
    status: "progress",
    details: {
      calls: 5,
      meetings: 2,
      emails: 4,
    },
    category: "secondary",
    location: "New York",
    amount: 8300000,
  },
  {
    id: 21,
    agent_name: "Alice Johnson",
    type: "invoiced",
    status: "onhold",
    details: {
      calls: 8,
      meetings: 3,
      emails: 7,
    },
    category: "offplan",
    location: "Miami",
    amount: 4200000,
  },
  {
    id: 22,
    agent_name: "Michael Smith",
    type: "uninvoiced",
    status: "won",
    details: {
      calls: 21,
      meetings: 7,
      emails: 15,
    },
    category: "secondary",
    location: "Los Angeles",
    amount: 9300000,
  },
  {
    id: 23,
    agent_name: "Jessica Brown",
    type: "invoiced",
    status: "progress",
    details: {
      calls: 12,
      meetings: 4,
      emails: 9,
    },
    category: "offplan",
    location: "Dubai Hills",
    amount: 3100000,
  },
  {
    id: 24,
    agent_name: "Robert Wilson",
    type: "uninvoiced",
    status: "onhold",
    details: {
      calls: 9,
      meetings: 3,
      emails: 8,
    },
    category: "secondary",
    location: "San Francisco",
    amount: 7200000,
  },
  {
    id: 25,
    agent_name: "Emma Thompson",
    type: "invoiced",
    status: "won",
    details: {
      calls: 10,
      meetings: 4,
      emails: 9,
    },
    category: "offplan",
    location: "Palm Jumeirah",
    amount: 6500000,
  },
  {
    id: 26,
    agent_name: "Daniel Martinez",
    type: "uninvoiced",
    status: "progress",
    details: {
      calls: 6,
      meetings: 2,
      emails: 5,
    },
    category: "secondary",
    location: "Beverly Hills",
    amount: 4000000,
  },
  {
    id: 27,
    agent_name: "Sophia Anderson",
    type: "invoiced",
    status: "onhold",
    details: {
      calls: 15,
      meetings: 5,
      emails: 12,
    },
    category: "offplan",
    location: "Dubai Marina",
    amount: 5800000,
  },
  {
    id: 28,
    agent_name: "David Scott",
    type: "uninvoiced",
    status: "won",
    details: {
      calls: 20,
      meetings: 6,
      emails: 14,
    },
    category: "secondary",
    location: "Miami",
    amount: 8700000,
  },
  {
    id: 29,
    agent_name: "Olivia King",
    type: "invoiced",
    status: "progress",
    details: {
      calls: 14,
      meetings: 5,
      emails: 11,
    },
    category: "offplan",
    location: "Downtown Dubai",
    amount: 7600000,
  },
  {
    id: 30,
    agent_name: "Lucas Walker",
    type: "uninvoiced",
    status: "onhold",
    details: {
      calls: 7,
      meetings: 3,
      emails: 6,
    },
    category: "secondary",
    location: "Abu Dhabi",
    amount: 2900000,
  },

  {
    id: 31,
    agent_name: "Alice Johnson",
    type: "invoiced",
    status: "won",
    details: {
      calls: 22,
      meetings: 8,
      emails: 17,
    },
    category: "offplan",
    location: "Business Bay",
    amount: 5900000,
  },
  {
    id: 32,
    agent_name: "Michael Smith",
    type: "uninvoiced",
    status: "progress",
    details: {
      calls: 9,
      meetings: 2,
      emails: 7,
    },
    category: "secondary",
    location: "New York",
    amount: 7700000,
  },
  {
    id: 33,
    agent_name: "Jessica Brown",
    type: "invoiced",
    status: "onhold",
    details: {
      calls: 12,
      meetings: 4,
      emails: 10,
    },
    category: "offplan",
    location: "Dubai Marina",
    amount: 4400000,
  },
  {
    id: 34,
    agent_name: "Robert Wilson",
    type: "uninvoiced",
    status: "won",
    details: {
      calls: 19,
      meetings: 6,
      emails: 13,
    },
    category: "secondary",
    location: "Los Angeles",
    amount: 9800000,
  },
  {
    id: 35,
    agent_name: "Emma Thompson",
    type: "invoiced",
    status: "progress",
    details: {
      calls: 11,
      meetings: 4,
      emails: 9,
    },
    category: "offplan",
    location: "Palm Jumeirah",
    amount: 5600000,
  },
  {
    id: 36,
    agent_name: "Daniel Martinez",
    type: "uninvoiced",
    status: "onhold",
    details: {
      calls: 10,
      meetings: 3,
      emails: 8,
    },
    category: "secondary",
    location: "Beverly Hills",
    amount: 7200000,
  },
  {
    id: 37,
    agent_name: "Sophia Anderson",
    type: "invoiced",
    status: "won",
    details: {
      calls: 18,
      meetings: 6,
      emails: 14,
    },
    category: "offplan",
    location: "Miami",
    amount: 8700000,
  },
  {
    id: 38,
    agent_name: "David Scott",
    type: "uninvoiced",
    status: "progress",
    details: {
      calls: 15,
      meetings: 5,
      emails: 11,
    },
    category: "secondary",
    location: "San Diego",
    amount: 6200000,
  },
  {
    id: 39,
    agent_name: "Olivia King",
    type: "invoiced",
    status: "onhold",
    details: {
      calls: 8,
      meetings: 3,
      emails: 7,
    },
    category: "offplan",
    location: "Downtown Dubai",
    amount: 3800000,
  },
  {
    id: 40,
    agent_name: "Lucas Walker",
    type: "uninvoiced",
    status: "won",
    details: {
      calls: 21,
      meetings: 7,
      emails: 16,
    },
    category: "secondary",
    location: "Abu Dhabi",
    amount: 6900000,
  },
  {
    id: 41,
    agent_name: "Alice Johnson",
    type: "invoiced",
    status: "progress",
    details: {
      calls: 6,
      meetings: 2,
      emails: 5,
    },
    category: "offplan",
    location: "Business Bay",
    amount: 2900000,
  },
  {
    id: 42,
    agent_name: "Michael Smith",
    type: "uninvoiced",
    status: "onhold",
    details: {
      calls: 12,
      meetings: 4,
      emails: 10,
    },
    category: "secondary",
    location: "New York",
    amount: 8400000,
  },
  {
    id: 43,
    agent_name: "Jessica Brown",
    type: "invoiced",
    status: "won",
    details: {
      calls: 16,
      meetings: 6,
      emails: 13,
    },
    category: "offplan",
    location: "Dubai Marina",
    amount: 5700000,
  },
  {
    id: 44,
    agent_name: "Robert Wilson",
    type: "uninvoiced",
    status: "progress",
    details: {
      calls: 9,
      meetings: 3,
      emails: 8,
    },
    category: "secondary",
    location: "Los Angeles",
    amount: 9100000,
  },
  {
    id: 45,
    agent_name: "Emma Thompson",
    type: "invoiced",
    status: "onhold",
    details: {
      calls: 11,
      meetings: 4,
      emails: 9,
    },
    category: "offplan",
    location: "Palm Jumeirah",
    amount: 6300000,
  },
  {
    id: 46,
    agent_name: "Daniel Martinez",
    type: "uninvoiced",
    status: "won",
    details: {
      calls: 19,
      meetings: 7,
      emails: 15,
    },
    category: "secondary",
    location: "Beverly Hills",
    amount: 9900000,
  },
  {
    id: 47,
    agent_name: "Sophia Anderson",
    type: "invoiced",
    status: "progress",
    details: {
      calls: 7,
      meetings: 2,
      emails: 6,
    },
    category: "offplan",
    location: "Miami",
    amount: 4700000,
  },
  {
    id: 48,
    agent_name: "David Scott",
    type: "uninvoiced",
    status: "onhold",
    details: {
      calls: 14,
      meetings: 5,
      emails: 11,
    },
    category: "secondary",
    location: "San Diego",
    amount: 6800000,
  },
  {
    id: 49,
    agent_name: "Olivia King",
    type: "invoiced",
    status: "won",
    details: {
      calls: 22,
      meetings: 8,
      emails: 17,
    },
    category: "offplan",
    location: "Downtown Dubai",
    amount: 7200000,
  },
  {
    id: 50,
    agent_name: "Lucas Walker",
    type: "uninvoiced",
    status: "progress",
    details: {
      calls: 10,
      meetings: 3,
      emails: 8,
    },
    category: "secondary",
    location: "Abu Dhabi",
    amount: 4600000,
  },
];
// --------------------------
// PRICING DATA MOCK
export const pricingData = {
  monthly: [
    {
      id: "agent",
      name: "Agent",
      price: 250,
      description: "Access to offplan and secondary listings.",
      features: [
        "Create secondary listing",
        "View offplan and secondary listing",
        "Interactive map",
        "Online presentations",
        "Developer contacts",
        "Fixing partner leads",
        "Educational materials",
        "PDF download options to share property details",
        "Access to multiple offplan properties and distress deals",
      ],
    },
    {
      id: "admin",
      name: "Admin",
      price: 300,
      description: "Includes all Agent features plus admin tools.",
      features: [
        "All from Agent plan",
        "Publish secondary listing on Bayut and Dubizzle",
        "Manage documents",
        "Download images to get permit number",
        "Bulk options",
        "Adding new listing for agent/owner",
        "Analytics",
        "Permission management",
      ],
    },
    {
      id: "super_admin",
      name: "Super Admin",
      price: 500,
      description: "Full control with advanced administrative features.",
      features: [
        "All from Admin plan",
        "Full access to all listings and modifications",
        "Advanced bulk listing management",
        "Complete permission and role management",
        "Company-wide analytics and reporting",
        "Custom branding options",
        "Priority support and dedicated account manager",
      ],
      popular: true,
    },
  ],
  yearly: [
    {
      id: "agent",
      name: "Agent",
      price: 2500,
      description: "Access to offplan and secondary listings.",
      features: [
        "Create secondary listing",
        "View offplan and secondary listing",
        "Interactive map",
        "Online presentations",
        "Developer contacts",
        "Fixing partner leads",
        "Educational materials",
        "PDF download options to share property details",
        "Access to multiple offplan properties and distress deals",
      ],
    },
    {
      id: "admin",
      name: "Admin",
      price: 3000,
      description: "Includes all Agent features plus admin tools.",
      features: [
        "All from Agent plan",
        "Publish secondary listing on Bayut and Dubizzle",
        "Manage documents",
        "Download images to get permit number",
        "Bulk options",
        "Adding new listing for agent/owner",
        "Analytics",
        "Permission management",
      ],
    },
    {
      id: "super_admin",
      name: "Super Admin",
      price: 5000,
      description: "Full control with advanced administrative features.",
      features: [
        "All from Admin plan",
        "Full access to all listings and modifications",
        "Advanced bulk listing management",
        "Complete permission and role management",
        "Company-wide analytics and reporting",
        "Custom branding options",
        "Priority support and dedicated account manager",
      ],
      popular: true,
    },
  ],
};
